// Tasks per role, as structured data: each is a job, why it matters, the inputs to
// paste, and the output shape as the function actually writes it. Everything else
// in the rendered prompt comes from the role in teams.data.js. Bracketed numbers
// cite the role's dossier under research/teams/.
//
// Field contract (buildPrompt.js reads every one of these):
//   job       one sentence
//   why       the reason, so the model can generalise from it
//   artefact  the plural noun for the examples slot ("design docs")
//   inputs    what to paste, one block each
//   output    the shape, section by section
//   check     optional extra rubric lines beyond the role's test
//   example   optional placeholder text for the picker's topic field

export const DATA_SCIENCE_TASKS = {
  id: "pl-team-data-science-tasks",
  team: "pl-team-data-science",
  eyebrow: "Data science",
  title: "Six tasks",
  summary: "Six jobs, each the exact copy-paste prompt (the topic left as a placeholder).",
  tasks: {
    "Experiment design": {
      job: "Turn a proposed change into a testable plan, sized and pre-registered before the test starts. [2][15][26]",
      why: "a test designed after the data arrives can only confirm what someone already wanted.",
      artefact: "experiment design docs",
      inputs: [
        "the hypothesis in one falsifiable sentence",
        "the metric roles and margins: success, guardrail with margin, deterioration, quality [15]",
        "the randomisation unit and the interference story",
        "baseline mean and variance, the minimum detectable effect, the org's prior success rate",
        "available traffic per day",
      ],
      output: [
        "Hypothesis",
        "Metric table: metric, role, test (superiority or non-inferiority), margin [15]",
        "Unit, and the interference note that justifies it [19][22]",
        "Sample size per variant with the formula shown: 16 times variance over the squared effect at 80 percent power [26]",
        "Duration, and the peeking regime (fixed horizon or sequential) [3][17]",
        "Ramp path: dogfood, beta, 1 to 5 to 10 percent [2]",
        "Stop rules",
      ],
      example: "showing the delivery slot before the cart",
    },
    "Experiment readout": {
      job: "Convert a scorecard into one decision: ship, abort, iterate, or unpowered. [3][4][15][16]",
      why: "a readout exists so the product manager can decide without opening the dashboard.",
      artefact: "experiment readouts",
      inputs: [
        "the configured split and the observed counts per variant",
        "per-metric deltas with confidence intervals and p-values",
        "the day-by-day treatment effect",
        "the pre-registered segments",
      ],
      output: [
        "Validity block first: sample ratio check, quality metrics, anything that invalidates the test [5][15]",
        "The decision line: ship, abort, iterate, or unpowered [16]",
        "Success and guardrail table, each with its interval and its test [15]",
        "Caveats: novelty, interference, triggering and dilution, denominator moves [3][4]",
        "What we learned, whichever way it went [16]",
      ],
      check: ["no number appears without its interval and its unit"],
      example: "the slot-first checkout test",
    },
    "Metric definition": {
      job: "Write a metric so that two teams querying it get one number. [6][14]",
      why: "before metrics were defined once, different teams reported different numbers for very simple business questions.",
      artefact: "metric definitions",
      inputs: ["the business question", "the event source", "the candidate denominators", "the segments it will be cut by"],
      output: [
        "Name and owner [14]",
        "Numerator, denominator, unit, and the direction that is good [6]",
        "The six-property assessment: sensitive, trustworthy, efficient, debuggable, interpretable, inclusive [6]",
        "Debug metrics that explain a move [6]",
        "Known failure modes, denominator shifts first [4]",
      ],
      example: "on-time delivery rate",
    },
    "Switchback or geo test plan": {
      job: "Design a test for a change where users interfere with each other: dispatch, surge, assortment, supply. [18][19][22]",
      why: "a user-level test on a dispatch change gave a 62 percent false-positive rate in simulation.",
      artefact: "switchback test plans",
      inputs: ["the regions or stores available", "the time-block length under consideration", "daily volume per unit", "the intra-cluster correlation, if known"],
      output: [
        "Unit definition: region by time block, or store by day [19][22]",
        "Block schedule and its randomisation",
        "Analysis method: cluster-robust errors or a multilevel model [19]",
        "Power at the unit level, with variance reduction if it applies [18]",
        "Carryover caveat and the washout between blocks",
      ],
      example: "the new batching policy",
    },
    "Forecast brief": {
      job: "Specify a forecast an ops team can act on, with the human adjustments as part of the model. [20][21]",
      why: "a forecast without a named channel for adjustments gets overridden in a spreadsheet nobody sees.",
      artefact: "forecast briefs",
      inputs: ["the target series with its date column", "granularity, horizon and cadence", "the events calendar", "who is allowed to adjust it, and how"],
      output: [
        "Spec table: target, granularity, horizon, cadence [21]",
        "Loss function and why it fits the decision [21]",
        "Backtest window",
        "Named variance sources: weather, holidays, campaigns [20]",
        "Adjustment protocol: who, when, how it is recorded [20]",
      ],
      example: "hourly orders per dark store, seven days out",
    },
    "Analysis memo": {
      job: "Answer a business question with evidence, bottom line first. [10]",
      why: "the reader decides from the first paragraph and reads the rest only to check it.",
      artefact: "analysis memos",
      inputs: ["the question", "the data available", "the prior beliefs in the room"],
      output: [
        "Bottom line, in two sentences",
        "Method, and the unit it was measured at",
        "Evidence, each number with its interval",
        "Caveats, and what would change the answer",
        "The next test",
      ],
      check: ["the bottom-line-first ordering is an inference from Netflix's memo culture, not a stated rule"],
      example: "why weekend cancellations rose in March",
    },
  },
};

export const PRODUCT_TASKS = {
  id: "pl-team-product-tasks",
  team: "pl-team-product",
  eyebrow: "Product",
  title: "Seven tasks",
  summary: "Seven jobs, each the exact copy-paste prompt (the topic left as a placeholder).",
  tasks: {
    "Press release and FAQ": {
      job: "Test an idea before building it by writing its launch announcement and the questions it raises. [30][32]",
      why: "if the press release cannot say what is meaningfully better, faster, easier or cheaper, it is not worth building.",
      artefact: "press releases",
      inputs: ["the customer and the problem", "the proposed benefit", "price and availability", "market size and unit economics notes", "dependencies"],
      output: [
        "Press release, under one page: heading, subheading, summary, problem, solution, a spokesperson quote, a customer quote, getting started [30]",
        "External FAQ [30]",
        "Internal FAQ: market size, economics, dependencies, feasibility [32]",
        "No corporate jargon anywhere [30]",
      ],
      example: "scheduled delivery for the weekly shop",
    },
    "Requirements one-pager": {
      job: "Align a team on a problem before a solution, with the non-goals and the target on the page. [33][34][48]",
      why: "the document is the decision, and a decision without non-goals grows until it fails.",
      artefact: "one-pagers",
      inputs: ["the problem evidence", "the audience", "the outcome baseline and target", "the constraints", "the candidate solution, if any"],
      output: [
        "Description, Problem, Why [33]",
        "Success: the outcome with baseline and target [33][37]",
        "Audience, What [33]",
        "Non-goals [48]",
        "The biggest of the four risks, and how discovery retires it [41]",
        "Kill criteria as states and dates [35]",
        "Open questions",
      ],
      example: "substitutions when an item is out of stock",
    },
    "Opportunity solution tree": {
      job: "Turn interview snapshots into a tree: outcome, opportunities, solutions, assumption tests. [37][38]",
      why: "opportunities invented at the whiteboard are solutions in disguise.",
      artefact: "opportunity solution trees",
      inputs: ["the outcome", "three or more interview snapshots"],
      output: [
        "Outcome at the root [37]",
        "Opportunity space, need-shaped, sized by how often each was heard [37][38]",
        "The target opportunity and why",
        "Two or three solutions to compare [37]",
        "Assumption tests for the riskiest one [37]",
      ],
      check: ["every opportunity passes 'is there more than one way to address this?' [37]"],
      example: "reducing first-order cancellations",
    },
    "Interview synthesis": {
      job: "Turn one interview into a snapshot the team can map into the tree. [38][39]",
      why: "a snapshot captures the moments in the story where the opportunities emerged, while the story is fresh.",
      artefact: "interview snapshots",
      inputs: ["the transcript or notes", "the participant's quick facts"],
      output: [
        "Quick facts [38]",
        "One memorable quote [38]",
        "The experience map, in words [38]",
        "Opportunities: needs only, never solutions [38]",
        "Insights",
      ],
      example: "the Tuesday evening interview with a two-child household",
    },
    "Prioritisation": {
      job: "Rank a backlog with the trade-offs visible and the exceptions declared. [36][43][45]",
      why: "a score without its working cannot be argued with, and a backlog nobody argues with is not prioritised.",
      artefact: "prioritisations",
      inputs: ["the items, each with reach per quarter, impact, confidence, effort in person-months", "the strategic must-dos"],
      output: [
        "The scoring table: reach, impact (3, 2, 1, 0.5, 0.25), confidence (100, 80, 50 percent), effort, score [43]",
        "Tiers: essentials, differentiators, not now [45]",
        "Declared exceptions and the reason for each [43]",
        "The opportunity cost of the top item [36]",
      ],
      example: "the Q3 checkout backlog",
    },
    "Launch and rollout plan": {
      job: "Ship to learn without harming the guardrails, with the kill decision made in advance. [2][35][44]",
      why: "a kill criterion set before launch is a decision; one made during launch is a fight.",
      artefact: "launch plans",
      inputs: ["the feature", "the stages available", "guardrail metrics and thresholds", "the owners"],
      output: [
        "Stage ladder: dogfood, beta, 1 to 5 to 10 percent [2]",
        "Per-stage guardrails and thresholds",
        "Kill criteria as states and dates, with owners [35]",
        "The learning goal of the launch [44]",
        "The one-line communication",
      ],
      example: "rider tipping at checkout",
    },
    "Release note": {
      job: "Tell customers what changed, in their words, and how to use it. [30][44]",
      why: "what you ship is what matters, and a note in the company's words is a note nobody reads.",
      artefact: "release notes",
      inputs: ["the change", "who it affects", "how to use it"],
      output: ["What changed", "Why it matters to the customer", "How to get started", "No jargon [30]"],
      check: ["this shape is a practice inference; no primary source for release notes was found"],
      example: "the new slot picker",
    },
  },
};

export const LAST_MILE_TASKS = {
  id: "pl-team-last-mile-tasks",
  team: "pl-team-last-mile",
  eyebrow: "Last mile",
  title: "Six tasks",
  summary: "Six jobs, each the exact copy-paste prompt (the topic left as a placeholder).",
  tasks: {
    "Weekly store review": {
      job: "Turn one week of store-level numbers into a ranked review with one action per outlier. [10][11]",
      why: "the network average hides the loss-making stores that drag it.",
      artefact: "store reviews",
      inputs: [
        "per store: orders per store per day, net order value, net average order value, contribution margin, for this week, last week and the same week last year",
        "each store's cohort",
        "a festive or weather flag for the week",
      ],
      output: [
        "Headline: the network delta in the house definition, with its window [10]",
        "Top five and bottom five stores, each with its cause named as supply or demand, and the lever [6][11]",
        "Owner and date per action",
      ],
      example: "week 36, Bengaluru south cluster",
    },
    "Breach root cause": {
      job: "Attribute a delivery-promise breach spike to its legs and the stress state, before proposing anything. [4][5][6]",
      why: "a fix aimed at the wrong leg buys nothing and costs a lateness price.",
      artefact: "breach root-cause notes",
      inputs: ["breach share by leg per store-hour", "the stress level log", "logins per zone", "the p90 of pick time"],
      output: [
        "Leg attribution table: assignment delay, first mile, prep or pick, wait, last mile, last-last mile [5][6]",
        "Supply column and demand column, each with its cause [6]",
        "One fix per leg, with the trade-off it accepts [2][4]",
      ],
      example: "Tuesday 7 to 9 pm at the Koramangala store",
    },
    "Rider supply plan": {
      job: "Size logins per zone per hour slot for the next week, and the incentive that closes each gap. [6][8][15]",
      why: "a gap in the 7 to 9 pm slot is a stress state, a serviceability cut, and a lost order, in that order.",
      artefact: "supply plans",
      inputs: ["the demand forecast by slot", "logins by slot for the last four weeks", "assignment delay by slot", "the planned incentives"],
      output: [
        "Slot by zone gap table [8]",
        "The incentive lever per gap: daily target, peak bonus, referral [15]",
        "The expected effect on assignment delay [6]",
      ],
      example: "next week's evening peaks in Hyderabad",
    },
    "Batching or dispatch memo": {
      job: "Argue one batching or delayed-dispatch change with its lateness price and its evidence plan. [1][2][4]",
      why: "every batching change trades the promise for efficiency, and a before-and-after cannot prove which won.",
      artefact: "dispatch memos",
      inputs: ["the current batch rate", "the lateness and earliness distribution", "rider wait at store", "order-ready-time accuracy"],
      output: [
        "The change, in one sentence",
        "Efficiency gain, with the number [2]",
        "Lateness cost, with the number [4]",
        "Switchback design: unit, block length, duration [1]",
        "Stop rule",
      ],
      example: "two-order picker batches at high-volume stores",
    },
    "Rate card review": {
      job: "Redesign a rider rate card for one city, tested against earnings after costs. [15][17][19][20]",
      why: "a payout that fails the minimum-wage-after-costs test fails the first fairness test the sector is scored on.",
      artefact: "rate card reviews",
      inputs: ["base pay and per-order add-ons", "daily and weekly targets and peak bonuses", "payout cadence", "rider earnings and costs", "the local minimum wage"],
      output: [
        "Current card next to the proposed card [19][20]",
        "Earnings after costs at three activity levels [17]",
        "Pass or fail against the local minimum wage [17]",
        "The festive variant [15]",
      ],
      example: "Pune, from October",
    },
    "Densification plan": {
      job: "Decide where the next stores go: densify, expand, or sweat existing capacity. [10][11]",
      why: "a store network runs at about half its stated capacity, so adding stores and sweating stores are competing bets.",
      artefact: "network plans",
      inputs: ["pin-code coverage and stores per serviceable pin code", "orders per store per day against capacity", "gross order value per square foot", "store margin cohort"],
      output: [
        "Densify list and expand list, each entry with the metric that justifies it [10][11]",
        "Ramp expectation by cohort [12]",
        "What is sweated instead of built",
      ],
      example: "Chennai, next two quarters",
    },
  },
};

export const DESIGN_LEADS_TASKS = {
  id: "pl-team-design-leads-tasks",
  team: "pl-team-design-leads",
  eyebrow: "Design leads",
  title: "Six tasks",
  summary: "Six jobs, each the exact copy-paste prompt (the topic left as a placeholder).",
  tasks: {
    "Run a critique": {
      job: "Analyse the work against its stated goals, by layer, without solving anything. [1][2][10]",
      why: "a critique that redesigns takes the decision away from the designer and skips the analysis.",
      artefact: "critiques",
      inputs: ["the goals and the stage of the work", "the ask and the non-ask, in the presenter's words", "the screens or flow", "the relevant principles"],
      output: [
        "The goals restated [1]",
        "Three to five clarifying questions, before any judgment [1][3]",
        "Observations grouped by layer: outcome, structure, interaction, visual, each tied to a goal [10]",
        "No solutions [2]",
      ],
      example: "the new slot picker flow",
    },
    "Design review decision": {
      job: "Decide whether the bar is met, from using the product, and say what must change. [7]",
      why: "a product goes mediocre through the small decisions nobody reviewed.",
      artefact: "review decisions",
      inputs: ["the friction log or walkthrough notes", "the essential journey under review", "the rubric"],
      output: [
        "Scores on utility, usability and beauty, each with its evidence from use [7]",
        "The bar: met or not",
        "What must change",
        "Ship, or hold [7]",
      ],
      example: "first order, from open to delivered",
    },
    "Design brief": {
      job: "Write the problem statement a team designs from: outcome, why, current pain. [10][11]",
      why: "a brief that names the feature instead of the outcome has already decided the design.",
      artefact: "design briefs",
      inputs: ["the customer", "the outcome they want and why", "the current pain", "constraints", "how success is measured"],
      output: [
        "One-page problem statement: customer, outcome, why, pain [11]",
        "Success measure [10]",
        "Out of scope",
        "Open questions",
      ],
      example: "reordering last week's basket",
    },
    "Quality rubric": {
      job: "Build the quality bar for one surface: axes, levels, and the evidence each level needs. [7]",
      why: "a bar written as adjectives cannot be scored twice the same way.",
      artefact: "quality rubrics",
      inputs: ["the essential journeys on this surface", "examples of the bar met and missed"],
      output: [
        "Axes: utility, usability, beauty [7]",
        "Levels per axis, named",
        "Evidence required per level, from friction logs [7]",
        "Review cadence",
      ],
      example: "the checkout surface",
    },
    "Hiring scorecard": {
      job: "Assess a candidate's case study and interview notes on the work and on the person. [5][6]",
      why: "the strongest candidates narrate what did not work; perfect-looking work is the red flag.",
      artefact: "hiring notes",
      inputs: ["the role and the ladder", "the case study", "the interview notes"],
      output: [
        "On the work: the idea, usability, craftsmanship [6]",
        "On the person: proactivity, critical thinking, thoughtfulness, collaboration [6]",
        "What they tried and abandoned [5]",
        "Hire signal, with the evidence",
      ],
      example: "senior product designer, growth",
    },
    "Performance feedback": {
      job: "Write feedback that quotes the rubric and sticks to dated, observed behaviour. [14][15]",
      why: "assumptions and judgments are the part a person cannot act on.",
      artefact: "performance reviews",
      inputs: ["the rubric or ladder text", "dated observations", "peer notes", "the person's own goals"],
      output: [
        "Rubric quotes, with the situation, behaviour and impact facts grouped under each [14]",
        "One growth ask",
        "Delivered in writing before the meeting, with the person's delivery preference asked first [14][15]",
      ],
      example: "mid-year, a designer two years in",
    },
  },
};

export const LEADERSHIP_TASKS = {
  id: "pl-team-leadership-tasks",
  team: "pl-team-leadership",
  eyebrow: "Company leadership",
  title: "Six tasks",
  summary: "Six jobs, each the exact copy-paste prompt (the topic left as a placeholder).",
  tasks: {
    "Strategy memo": {
      job: "Write the kernel: a diagnosis, a guiding policy, coherent actions, and the possibilities rejected. [16][17][18]",
      why: "goals dressed as strategy are the first hallmark of bad strategy.",
      artefact: "strategy memos",
      inputs: ["the challenge as you see it", "the facts on customers and competitors", "the candidate possibilities", "constraints, and what has been tried"],
      output: [
        "Diagnosis, naming the obstacle [16]",
        "Guiding policy: what it constrains, and so what will not be done [16]",
        "Coherent actions [16]",
        "Rejected possibilities, each with what would have to be true [17][18]",
        "Proximate objectives [16]",
      ],
      example: "the next twelve months in tier-two cities",
    },
    "Six-pager": {
      job: "Draft a narrative memo for a silent read: prose, an appendix for the data, and the sentences most likely to be challenged. [21][22][23]",
      why: "the room assumes each sentence is wrong until proven, and a good memo is rewritten over a week.",
      artefact: "narrative memos",
      inputs: ["the customer and the problem", "the proposal", "the data for the appendix", "the hard questions the room will ask"],
      output: [
        "Six pages of prose, no bullets [22][23]",
        "The FAQ [22]",
        "Appendix list",
        "The three sentences most likely to be challenged, and their evidence",
      ],
      example: "entering pharmacy delivery",
    },
    "Board update": {
      job: "Write the board pack with the bad news and the asks in their own slots. [26][27]",
      why: "a pack that hides its shortcomings pushes the real story into side conversations.",
      artefact: "board updates",
      inputs: ["the period's metrics", "wins and misses", "cash and runway", "the asks"],
      output: [
        "Highlights, then lowlights [26]",
        "The fewest correct metrics that tell the story [26]",
        "Company building",
        "Where we need help [26]",
        "The proposed working session, with most of the time on the future [27]",
      ],
      example: "Q3 board meeting",
    },
    "Decision memo": {
      job: "Classify the decision by its door and make the call at about 70 percent of the information. [19][20]",
      why: "being slow is expensive for sure, and being wrong may be less costly than it looks.",
      artefact: "decision memos",
      inputs: ["the options", "the reversibility and cost of reversing each", "the information available now versus later", "who is accountable, and dissent on record"],
      output: [
        "Door type: one-way or two-way [19]",
        "Recommendation",
        "What 70 percent of the information looks like here [20]",
        "The cost of delay [20]",
        "The decider, and dissent recorded as disagree and commit [20]",
      ],
      example: "whether to build our own rider app",
    },
    "Objectives and key results": {
      job: "Set three to five objectives with numeric, dated key results, each tagged committed or aspirational. [24][25]",
      why: "a key result without a number and a date is a wish, and one that lands on the last day of the quarter is not a plan.",
      artefact: "objective sets",
      inputs: ["the company objectives", "the team's scope", "the baseline numbers"],
      output: [
        "Three to five objectives, one line each [24][25]",
        "About three key results per objective, each with a number and a date [24]",
        "Committed or aspirational, per objective, with the expected score [25]",
        "Sandbag check: anything that is business as usual [24][25]",
      ],
      example: "the operations team, Q4",
    },
    "Hard message": {
      job: "Write the message for a layoff or a missed plan, for the people who stay. [28]",
      why: "the message is read by everyone who remains, and they decide whether to trust the next one.",
      artefact: "hard messages",
      inputs: ["the plan miss and its cause", "who is affected", "benefits details", "what changes for those who stay"],
      output: [
        "The all-company message, from the chief executive, saying the company failed to hit its plan [28]",
        "Manager talking points, since managers speak to their own people [28]",
        "What not to say",
      ],
      example: "closing two cities",
    },
  },
};

export const BACKEND_TASKS = {
  id: "pl-team-backend-tasks",
  team: "pl-team-backend",
  eyebrow: "Backend engineering",
  title: "Seven tasks",
  summary: "Seven jobs, each the exact copy-paste prompt (the topic left as a placeholder).",
  tasks: {
    "Design doc": {
      job: "Turn a problem statement into a Google-style design doc: the trade-offs written down before the code exists. [6]",
      why: "the doc is where the trade-offs get argued once, in the open, instead of rediscovered in review.",
      artefact: "design docs",
      inputs: [
        "the problem statement",
        "the current system: services, stores, and a diagram in text",
        "constraints and forces (latency, cost, compliance, deadlines)",
        "options already known",
        "who reviews it",
      ],
      output: [
        "Context and scope",
        "Goals, then Non-goals (things that could reasonably be goals and are explicitly not) [6]",
        "Design: overview, then system-context diagram in text, APIs, storage [6]",
        "Alternatives considered, each with the trade-off that decided against it [6]",
        "Cross-cutting concerns: security, privacy, observability [6]",
        "Open questions",
      ],
      example: "moving order status to an event stream",
    },
    "Architecture decision record": {
      job: "Record one architecture decision so a future developer can read the conversation that led to it. [12]",
      why: "an ADR that is never edited, only superseded, keeps the reasoning alive after the people leave.",
      artefact: "ADRs",
      inputs: ["the forces, stated neutrally", "the options on the table", "the decision taken, if already made"],
      output: [
        "Title: a short noun phrase",
        "Context: the forces, value-neutral [12]",
        "Decision: 'We will', in the active voice [12]",
        "Status: proposed, accepted, deprecated or superseded [12]",
        "Consequences: every one, the negative ones included [12]",
        "Supersedes: the earlier record, if any",
      ],
      example: "Postgres over DynamoDB for the rider ledger",
    },
    "Code review": {
      job: "Review a change for code health, with every comment labelled and explained. [1][2][16]",
      why: "the author must know what blocks the merge and what is a nit, and why.",
      artefact: "review comments",
      inputs: ["the diff", "the change description: what and why, known shortcomings [4]", "the style guide, or a link to it"],
      output: [
        "One verdict: approve, approve with nits, or request changes [1]",
        "Comments in Conventional Comments form: label (decoration): subject, then why; blocking and non-blocking never in one comment [16]",
        "Design first, then functionality, complexity, tests, naming, comments, style, consistency, docs [3]",
        "At least one thing that is good, said specifically [2]",
      ],
      check: ["every comment is about the code, not the developer [2]"],
      example: "the batching service PR",
    },
    "Retry and idempotency spec": {
      job: "Define the retry policy for one call path so a retry can never become a duplicate side effect. [13][15][20]",
      why: "a retry that is not safe is a second charge or a second dispatch.",
      artefact: "retry specs",
      inputs: ["the endpoint and its side effects", "the dependency's error codes", "its latency histogram", "what the caller shows the user on failure today"],
      output: [
        "Idempotency key: header, generation (V4 UUID), lifetime, and the behaviour on parameter mismatch [13][14]",
        "Retryable codes, and the codes never retried [20]",
        "Base, cap, attempts, and the full-jitter formula: sleep = random(0, min(cap, base times 2 to the attempt)) [15]",
        "Circuit breaker thresholds and what is logged on each state change [23]",
        "What the caller shows the user on final failure",
      ],
      example: "the payment capture call",
    },
    "Blameless post-mortem": {
      job: "Write the incident record: impact, timeline, systemic causes, and the actions that stop it recurring. [7]",
      why: "a post-mortem exists to change the system, and a name attached to a cause ends that.",
      artefact: "post-mortems",
      inputs: ["the timeline with timestamps", "impact metrics (orders, minutes, money)", "how it was detected", "what was tried, in order"],
      output: [
        "Summary",
        "Impact, in numbers [7]",
        "Timeline",
        "Contributing causes, systemic, no names [7]",
        "What went well; what went wrong",
        "Action items: item, owner, priority, due [7]",
        "Lessons",
      ],
      example: "the 14 March dispatch outage",
    },
    "SLO and error budget policy": {
      job: "Define the SLIs and SLOs for one user journey, and what happens when the budget runs out. [8][9]",
      why: "reliability becomes a spendable number only once the policy for exhaustion is written down.",
      artefact: "SLO documents",
      inputs: ["the user journey", "what counts as a valid event and a good event [9]", "current latency histograms", "the business consequence of a miss"],
      output: [
        "SLI: good events over valid events [9]",
        "SLO: target, window, and the rationale behind the number [9]",
        "Error budget and how it is calculated [8]",
        "Policy: the actions on exhaustion, and the escalation path [9]",
        "Owners, reviewers and the review date [9]",
      ],
      check: ["the target is not a copy of current performance and contains no 'always' [8]"],
      example: "order placement",
    },
    "Migration plan": {
      job: "Plan a zero-downtime data model change in Stripe's four phases, with a rollback per phase. [17][18]",
      why: "a migration without a rollback point is a bet on nothing going wrong in production.",
      artefact: "migration plans",
      inputs: ["the old and new models", "the read and write paths", "data volume", "the rollback point"],
      output: [
        "Phase 1: dual write [18]",
        "Phase 2: read cut-over with a comparison experiment [18]",
        "Phase 3: write cut-over [18]",
        "Phase 4: delete the old data [18]",
        "Backfill method from snapshots, offline [18]",
        "Verification job and rollback per phase",
        "Flag kind, who flips it, and its removal date [17]",
      ],
      example: "splitting the orders table by city",
    },
  },
};

export const FRONTEND_TASKS = {
  id: "pl-team-frontend-tasks",
  team: "pl-team-frontend",
  eyebrow: "Frontend engineering",
  title: "Six tasks",
  summary: "Six jobs, each the exact copy-paste prompt (the topic left as a placeholder).",
  tasks: {
    "Component spec from Figma": {
      job: "Turn a Dev Mode node into a build-ready spec, on tokens, with every state named. [39][43]",
      why: "a spec that lists every part and state is the difference between one build and three rounds of QA.",
      artefact: "component specs",
      inputs: ["the Dev Mode export: specs, variables, annotations [43]", "the token file [39]", "the library's naming conventions", "any Code Connect mapping [43]"],
      output: [
        "Anatomy: the named parts",
        "Props table: name, type, default, controlled or not [37]",
        "Variants and sizes",
        "States: default, hover, pressed, focus, disabled, loading, empty, error",
        "Spacing, as token aliases [39]",
        "Behaviour: the keyboard model and focus handling [32]",
        "Content rules, and open questions for design",
      ],
      example: "the slot picker sheet",
    },
    "State matrix": {
      job: "Enumerate every UI state for one screen or component, and what happens on failure or revert. [36][38][44]",
      why: "the state nobody designed is the one users meet on a slow network.",
      artefact: "state matrices",
      inputs: ["the data source and its latency profile", "what can fail and how", "what empty means in this domain"],
      output: [
        "A table, one row per state: state, trigger, what renders (skeleton, real content, message), what the user can do, what happens on failure or revert, the token and copy it uses",
        "Loading rendered as a skeleton of the coming layout [44]",
        "Optimistic rows that name the revert [38]",
        "Derived state marked as computed, never stored [36]",
      ],
      example: "the order tracking screen",
    },
    "Accessibility pass": {
      job: "Audit a component against the ARIA Authoring Practices and WCAG 2.2, judged by keyboard and focus, not by attributes. [32][33][34][35]",
      why: "no ARIA is better than bad ARIA, and roles add no behaviour on their own.",
      artefact: "accessibility audits",
      inputs: ["the markup or React Native tree", "the intended pattern (dialog, menu, tabs, listbox)", "target platforms and assistive tech"],
      output: [
        "Keyboard model table: key, action [32]",
        "Focus: where it goes on open, whether it is trapped, where it returns [33]",
        "The roles and names actually needed, and the ones to remove [34]",
        "Target size check against 24 by 24 CSS px [35]",
        "Reduced-motion check [41]",
        "Findings labelled blocking or non-blocking, each with why [16]",
      ],
      example: "the address search dialog",
    },
    "Performance budget": {
      job: "Set the vitals budget for one route and decide what to optimise, remove or decline. [27][31]",
      why: "a budget enforced in CI is the only version of 'keep it light' that survives the next feature.",
      artefact: "performance budgets",
      inputs: ["current p75 LCP, INP and CLS from the field [27]", "the bundle report", "the device and network class of users"],
      output: [
        "The LCP element and its load path [28]",
        "The hot interactions for INP, and which phase (input delay, processing, presentation) to cut [29]",
        "CLS causes and their reservations: dimensions, aspect-ratio, font-display, transform [30]",
        "Budget table: metric, limit, CI gate [31]",
        "For anything over: optimise, remove, or decline, with the reason [31]",
      ],
      example: "the home feed",
    },
    "Code review": {
      job: "Review a UI change for code health, with every comment labelled and explained. [1][2][16]",
      why: "the author must know what blocks the merge and what is a nit, and why.",
      artefact: "review comments",
      inputs: ["the diff", "the change description", "the token file"],
      output: [
        "One verdict: approve, approve with nits, or request changes [1]",
        "Conventional Comments per finding: label (decoration): subject, then why [16]",
        "Checked in this order: derived state in Effects, token literals, missing states, keyboard and focus, layout-shift risks [30][32][36][39]",
        "At least one thing that is good, said specifically [2]",
      ],
      example: "the cart redesign PR",
    },
    "Rollout plan": {
      job: "Ship a React Native update to a share of users first, with the revert ready. [46]",
      why: "a rollout percentage turns a bad release into a small one.",
      artefact: "rollout plans",
      inputs: ["the branch or channel", "the blast radius of the change", "the revert command"],
      output: [
        "Rollout percentage steps [46]",
        "The metric watched at each step, and its threshold",
        "The revert trigger and the exact command [46]",
        "Who flips it, and when the rollout is called done",
      ],
      check: ["the metric-watch clause is a practice inference, not a vendor rule; state it as the team's own"],
      example: "the new checkout sheet",
    },
  },
};

export const TASK_SETS = [DATA_SCIENCE_TASKS, PRODUCT_TASKS, LAST_MILE_TASKS, BACKEND_TASKS, FRONTEND_TASKS, DESIGN_LEADS_TASKS, LEADERSHIP_TASKS];
