// Airplane views: the system spec is prose, but the fleet roster is DERIVED from
// the recipe's own AIRCRAFT list rather than stored.
//
// It used to be generated by Claude/Prompt Library/build-airplane-roster.mjs, which
// spliced text into the old monolith. That made the spec's own promise ("adding a
// family in airplaneViews.js adds it to both the picker and this list at once") true
// only if someone remembered to re-run the script. Composing it here makes it true.
import { AIRCRAFT, GROUPS } from "./airplaneViews.js";
import { SPECS } from "./airplanes.data.js";

const system = SPECS.find((s) => s.id === "pl-airplane-views-system");
const fleet = SPECS.find((s) => s.id === "pl-airplane-views-fleet");

// `desc` is written to sit mid-sentence inside a composed prompt ("...illustration
// of the Airbus A220"), so it opens lowercase; as a list entry it is sentence case.
const asEntry = (s) => s.charAt(0).toUpperCase() + s.slice(1);

const roster = Object.fromEntries(
  GROUPS.map((g) => [g, AIRCRAFT.filter((a) => a.group === g).map((a) => asEntry(a.desc))])
);

export const airplaneSpecs = [
  system,
  {
    id: fleet.id,
    group: fleet.group,
    eyebrow: fleet.eyebrow,
    title: fleet.title,
    summary: fleet.summary,
    "How the roster works": fleet["How the roster works"],
    ...roster,
  },
];
