// Image-generation prompts: Doodle hands.
// { pre } blocks carrying rules:true get the library rules appended at assembly.
// Part of the prompt library (src/prd/promptLibrary). See index.js for the map.

export const SPECS = [
  {
    "id": "pl-hands-system",
    "group": "Doodle hands",
    "eyebrow": "Hands",
    "title": "Doodle hands · the system",
    "summary": "Puffy four-fingered cartoon hands in one thin black pen line, matching the hands reference sheet: plump bulbous fingers, flat white fill, springy exaggerated poses, plain white background. Built for Nano Banana 2 inside Figma; attach the reference sheet for an exact style match.",
    "What this is": [
      "Twenty-five sheet-replication prompts (one per cell of the reference sheet, for regenerating those exact poses), twelve freeform gesture prompts (six signals, six actions), and a master template with a swappable [GESTURE] dial.",
      "The look is constant and matches the 25-pose hands reference sheet: one thin even pen line, puffy four-fingered cartoon hands, flat white fill, no shading, no colour. Only the gesture, the direction, and an optional prop change.",
      "Distilled from the reference sheet: fine near-black line of even weight, marshmallow-soft palms, chubby bulbous fingers with knuckle bumps, open trailing wrists, exaggerated cartoon poses, minimal interior detail."
    ],
    "The constant": [
      "Drawn with a fine monoline pen in near-black (#1A1A1A): uniform stroke width throughout, no pressure taper and no swelling on the shadow side, softly rounded ends. Long confident single strokes with follow-through and a slight hand-drawn wobble, small open gaps where strokes meet, never scratchy or repeated searching lines. Never a thick marker.",
      "Exactly four digits: three fingers and one thumb, four in total, each digit clearly separate with visible negative space between them, every one a soft bulbous shape with a rounded tip. Built with mitten construction: one plump rounded palm mass, then a grouped finger mitten split into soft sausage forms, and a trowel-shaped thumb on a triangular base at the side of the palm, with the little finger placed off the rhythm of the other three. Knuckles softened away: no nails, no palm creases, no fingerprints.",
      "Puffy, marshmallow-soft anatomy in the rubber-hose cartoon idiom: a jointless tube-like wrist, continuous curves and no hard angles anywhere. One clear line of action running from wrist to fingertip, and the pose reads instantly as a solid black silhouette. Where the hand closes or squeezes it squashes at constant volume, the same mass as the open hand.",
      "Flat plain white fill inside every shape. No shading, no hatching, no gradients, no colour, no texture. No fingernails, no skin tone.",
      "The wrist is left open, its two contour lines simply trailing off with no closed stump and no cuff. Interior detail capped at one or two short single-stroke creases.",
      "Plain pure white background, the hand isolated and centred with generous padding, crisp and sharp. No text, no branding."
    ],
    "The dials": [
      "Gesture: what the hand is doing. Pick from the twelve below or describe your own in one plain sentence.",
      "Hand and direction: left or right hand, and which way it points or faces. Cheaper to mirror in Figma than to regenerate.",
      "Prop: anything the hand holds is drawn in the same single-outline doodle style with a plain white fill (phone, pencil, mug, token).",
      "Motion strokes: two or three short strokes in the same ink for waves, taps, bumps and claps; drop them for still poses."
    ],
    "How to use it in Figma": [
      "Best match: attach the 25-pose hands reference sheet alongside the prompt so Nano Banana 2 locks the exact line weight, finger proportions and character.",
      "Generate square, one hand per image. The plain white ground makes the cutout trivial.",
      "Need the same gesture facing the other way? Flip the layer in Figma instead of regenerating.",
      "Keep one generated hand you like and feed it back as the reference for every further gesture, so the whole set stays one family."
    ],
    "Copy-paste template": {
      "pre": "A hand-drawn doodle illustration of a single cartoon hand [GESTURE]. Drawn in a fine cartoon doodle style: a single thin, even-weight near-black pen line (#1A1A1A) with smooth confident curves, softly rounded ends and a slight hand-drawn wobble. The hand is puffy and marshmallow-soft: a plump rounded palm and exactly four chubby fingers in total (three fingers plus a thumb), every finger a soft bulbous shape with a rounded tip, with small overlapping knuckle bumps where fingers curl. Flat plain white fill inside every shape, no shading, no hatching, no gradients, no colour and no texture. The pose is springy and exaggerated with playful cartoon energy; interior detail is minimal, at most one or two short single-stroke lines for a crease. No fingernails, no skin tone, and the wrist is left open, its two contour lines simply trailing off with no closed stump and no cuff. The whole drawing reads as a light, springy pen cartoon with real charm, NOT a thick marker doodle, NOT a realistic hand and NOT a clean geometric vector icon. Plain pure white background, the hand isolated and centred with generous padding, crisp and sharp. If the reference hands sheet is attached, match its exact line weight, ink colour, finger proportions and hand-drawn character. {{RULES}}\n\n[GESTURE] options: pointing to the right with the index finger extended | giving a thumbs up | waving hello with an open palm | making a peace sign | making an OK sign | held out sideways in a fist bump | holding up a smartphone with a blank screen | tapping downward with the index finger | writing with a plain pencil | holding a round coffee mug by the handle | pinching a small round token between thumb and index finger | two hands clapping."
    },
    "Sources": [
      "Retuned 2026-08-15 against research/hands.md: four digits is Disney's own economy decision, mitten construction (palm mass, grouped finger mitten, trowel thumb on a triangular base) is the published Preston Blair and Proko build order, monoline is the correct name for an untapered pen line, and the silhouette test is the profession's own acceptance check. Note: the V sign and the OK sign carry real offence risk depending on palm direction and region, so gesture prompts should state palm orientation.",
      "Style reference: the 25-pose cartoon hands sheet (thin-line, four-fingered), part of the portfolio's doodle character set.",
      "Tuned for Nano Banana 2 in Figma, or any image model."
    ]
  },
  {
    "id": "pl-hands-sheet",
    "group": "Doodle hands",
    "eyebrow": "Hands",
    "title": "The sheet · all 25 poses",
    "summary": "One prompt per cell of the 25-pose hands reference sheet, row by row from the top left. Attach the sheet image with every prompt; the row and column index does the exact targeting and the pose description is the fallback if the model miscounts. Each hand is regenerated isolated, in the house style, with exactly four fingers.",
    "How to use": [
      "Attach the 25-pose sheet image alongside the prompt, every time. The prompt names a cell by row and column; without the sheet there is nothing to replicate.",
      "Generate square, one hand per image, and expect the four-finger conversion: the sheet cell is the pose truth, the prompt normalises the anatomy to three fingers plus a thumb.",
      "If the model picks the wrong cell, lean on the pose description in the prompt, or crop the sheet to the single cell and attach that instead.",
      "Mirror finished hands in Figma for opposite-direction variants instead of regenerating."
    ],
    "R1C1 · Thumb-out fist": {
      "pre": "Attached as reference is a sheet of 25 hand-drawn cartoon hand poses in a 5 by 5 grid. Recreate exactly the hand at row 1, column 1, counting from the top left: a side-on closed fist arriving from the left, the thumb resting along the top and pointing forward. Reproduce that cell's pose, camera angle, finger curl and line character faithfully, as one single isolated hand, with one change: give the hand exactly four fingers in total. Drawn in a fine cartoon doodle style: a single thin, even-weight near-black pen line (#1A1A1A) with smooth confident curves, softly rounded ends and a slight hand-drawn wobble. The hand is puffy and marshmallow-soft: a plump rounded palm and exactly four chubby fingers in total (three fingers plus a thumb), every finger a soft bulbous shape with a rounded tip, with small overlapping knuckle bumps where fingers curl. Flat plain white fill inside every shape, no shading, no hatching, no gradients, no colour and no texture. The pose is springy and exaggerated with playful cartoon energy; interior detail is minimal, at most one or two short single-stroke lines for a crease. No fingernails, no skin tone, and the wrist is left open, its two contour lines simply trailing off with no closed stump. The whole drawing reads as a light, springy pen cartoon with real charm, NOT a thick marker doodle, NOT a realistic hand and NOT a clean geometric vector icon. Plain pure white background, the hand isolated and centred with generous padding, crisp and sharp. Match the attached sheet exactly: the same line weight, ink colour, finger proportions and hand-drawn character.",
      "rules": true
    },
    "R1C2 · Raised palm": {
      "pre": "Attached as reference is a sheet of 25 hand-drawn cartoon hand poses in a 5 by 5 grid. Recreate exactly the hand at row 1, column 2, counting from the top left: an upright open palm seen slightly from the side, fingers together and gently cupped, raised as if about to high-five or signal stop. Reproduce that cell's pose, camera angle, finger curl and line character faithfully, as one single isolated hand, with one change: give the hand exactly four fingers in total. Drawn in a fine cartoon doodle style: a single thin, even-weight near-black pen line (#1A1A1A) with smooth confident curves, softly rounded ends and a slight hand-drawn wobble. The hand is puffy and marshmallow-soft: a plump rounded palm and exactly four chubby fingers in total (three fingers plus a thumb), every finger a soft bulbous shape with a rounded tip, with small overlapping knuckle bumps where fingers curl. Flat plain white fill inside every shape, no shading, no hatching, no gradients, no colour and no texture. The pose is springy and exaggerated with playful cartoon energy; interior detail is minimal, at most one or two short single-stroke lines for a crease. No fingernails, no skin tone, and the wrist is left open, its two contour lines simply trailing off with no closed stump. The whole drawing reads as a light, springy pen cartoon with real charm, NOT a thick marker doodle, NOT a realistic hand and NOT a clean geometric vector icon. Plain pure white background, the hand isolated and centred with generous padding, crisp and sharp. Match the attached sheet exactly: the same line weight, ink colour, finger proportions and hand-drawn character.",
      "rules": true
    },
    "R1C3 · Dangle": {
      "pre": "Attached as reference is a sheet of 25 hand-drawn cartoon hand poses in a 5 by 5 grid. Recreate exactly the hand at row 1, column 3, counting from the top left: a relaxed hand hanging straight down from above, the fingers dangling loosely together. Reproduce that cell's pose, camera angle, finger curl and line character faithfully, as one single isolated hand, with one change: give the hand exactly four fingers in total. Drawn in a fine cartoon doodle style: a single thin, even-weight near-black pen line (#1A1A1A) with smooth confident curves, softly rounded ends and a slight hand-drawn wobble. The hand is puffy and marshmallow-soft: a plump rounded palm and exactly four chubby fingers in total (three fingers plus a thumb), every finger a soft bulbous shape with a rounded tip, with small overlapping knuckle bumps where fingers curl. Flat plain white fill inside every shape, no shading, no hatching, no gradients, no colour and no texture. The pose is springy and exaggerated with playful cartoon energy; interior detail is minimal, at most one or two short single-stroke lines for a crease. No fingernails, no skin tone, and the wrist is left open, its two contour lines simply trailing off with no closed stump. The whole drawing reads as a light, springy pen cartoon with real charm, NOT a thick marker doodle, NOT a realistic hand and NOT a clean geometric vector icon. Plain pure white background, the hand isolated and centred with generous padding, crisp and sharp. Match the attached sheet exactly: the same line weight, ink colour, finger proportions and hand-drawn character.",
      "rules": true
    },
    "R1C4 · Point left": {
      "pre": "Attached as reference is a sheet of 25 hand-drawn cartoon hand poses in a 5 by 5 grid. Recreate exactly the hand at row 1, column 4, counting from the top left: a side-on hand pointing left, the index finger extended level, the other fingers curled under and the thumb tucked over them. Reproduce that cell's pose, camera angle, finger curl and line character faithfully, as one single isolated hand, with one change: give the hand exactly four fingers in total. Drawn in a fine cartoon doodle style: a single thin, even-weight near-black pen line (#1A1A1A) with smooth confident curves, softly rounded ends and a slight hand-drawn wobble. The hand is puffy and marshmallow-soft: a plump rounded palm and exactly four chubby fingers in total (three fingers plus a thumb), every finger a soft bulbous shape with a rounded tip, with small overlapping knuckle bumps where fingers curl. Flat plain white fill inside every shape, no shading, no hatching, no gradients, no colour and no texture. The pose is springy and exaggerated with playful cartoon energy; interior detail is minimal, at most one or two short single-stroke lines for a crease. No fingernails, no skin tone, and the wrist is left open, its two contour lines simply trailing off with no closed stump. The whole drawing reads as a light, springy pen cartoon with real charm, NOT a thick marker doodle, NOT a realistic hand and NOT a clean geometric vector icon. Plain pure white background, the hand isolated and centred with generous padding, crisp and sharp. Match the attached sheet exactly: the same line weight, ink colour, finger proportions and hand-drawn character.",
      "rules": true
    },
    "R1C5 · Reach down": {
      "pre": "Attached as reference is a sheet of 25 hand-drawn cartoon hand poses in a 5 by 5 grid. Recreate exactly the hand at row 1, column 5, counting from the top left: a hand reaching down from above, the fingers spread and dangling open as if about to grab. Reproduce that cell's pose, camera angle, finger curl and line character faithfully, as one single isolated hand, with one change: give the hand exactly four fingers in total. Drawn in a fine cartoon doodle style: a single thin, even-weight near-black pen line (#1A1A1A) with smooth confident curves, softly rounded ends and a slight hand-drawn wobble. The hand is puffy and marshmallow-soft: a plump rounded palm and exactly four chubby fingers in total (three fingers plus a thumb), every finger a soft bulbous shape with a rounded tip, with small overlapping knuckle bumps where fingers curl. Flat plain white fill inside every shape, no shading, no hatching, no gradients, no colour and no texture. The pose is springy and exaggerated with playful cartoon energy; interior detail is minimal, at most one or two short single-stroke lines for a crease. No fingernails, no skin tone, and the wrist is left open, its two contour lines simply trailing off with no closed stump. The whole drawing reads as a light, springy pen cartoon with real charm, NOT a thick marker doodle, NOT a realistic hand and NOT a clean geometric vector icon. Plain pure white background, the hand isolated and centred with generous padding, crisp and sharp. Match the attached sheet exactly: the same line weight, ink colour, finger proportions and hand-drawn character.",
      "rules": true
    },
    "R2C1 · Punch fist": {
      "pre": "Attached as reference is a sheet of 25 hand-drawn cartoon hand poses in a 5 by 5 grid. Recreate exactly the hand at row 2, column 1, counting from the top left: a tight clenched fist arriving from the upper left, the knuckles bunched forward. Reproduce that cell's pose, camera angle, finger curl and line character faithfully, as one single isolated hand, with one change: give the hand exactly four fingers in total. Drawn in a fine cartoon doodle style: a single thin, even-weight near-black pen line (#1A1A1A) with smooth confident curves, softly rounded ends and a slight hand-drawn wobble. The hand is puffy and marshmallow-soft: a plump rounded palm and exactly four chubby fingers in total (three fingers plus a thumb), every finger a soft bulbous shape with a rounded tip, with small overlapping knuckle bumps where fingers curl. Flat plain white fill inside every shape, no shading, no hatching, no gradients, no colour and no texture. The pose is springy and exaggerated with playful cartoon energy; interior detail is minimal, at most one or two short single-stroke lines for a crease. No fingernails, no skin tone, and the wrist is left open, its two contour lines simply trailing off with no closed stump. The whole drawing reads as a light, springy pen cartoon with real charm, NOT a thick marker doodle, NOT a realistic hand and NOT a clean geometric vector icon. Plain pure white background, the hand isolated and centred with generous padding, crisp and sharp. Match the attached sheet exactly: the same line weight, ink colour, finger proportions and hand-drawn character.",
      "rules": true
    },
    "R2C2 · Claw grip": {
      "pre": "Attached as reference is a sheet of 25 hand-drawn cartoon hand poses in a 5 by 5 grid. Recreate exactly the hand at row 2, column 2, counting from the top left: a hand arched over from below, the fingers curled downward like a claw gripping over the top of something. Reproduce that cell's pose, camera angle, finger curl and line character faithfully, as one single isolated hand, with one change: give the hand exactly four fingers in total. Drawn in a fine cartoon doodle style: a single thin, even-weight near-black pen line (#1A1A1A) with smooth confident curves, softly rounded ends and a slight hand-drawn wobble. The hand is puffy and marshmallow-soft: a plump rounded palm and exactly four chubby fingers in total (three fingers plus a thumb), every finger a soft bulbous shape with a rounded tip, with small overlapping knuckle bumps where fingers curl. Flat plain white fill inside every shape, no shading, no hatching, no gradients, no colour and no texture. The pose is springy and exaggerated with playful cartoon energy; interior detail is minimal, at most one or two short single-stroke lines for a crease. No fingernails, no skin tone, and the wrist is left open, its two contour lines simply trailing off with no closed stump. The whole drawing reads as a light, springy pen cartoon with real charm, NOT a thick marker doodle, NOT a realistic hand and NOT a clean geometric vector icon. Plain pure white background, the hand isolated and centred with generous padding, crisp and sharp. Match the attached sheet exactly: the same line weight, ink colour, finger proportions and hand-drawn character.",
      "rules": true
    },
    "R2C3 · Sprinkle": {
      "pre": "Attached as reference is a sheet of 25 hand-drawn cartoon hand poses in a 5 by 5 grid. Recreate exactly the hand at row 2, column 3, counting from the top left: a hand reaching down from the upper right, the fingertips pinched together pointing down as if picking up or sprinkling something. Reproduce that cell's pose, camera angle, finger curl and line character faithfully, as one single isolated hand, with one change: give the hand exactly four fingers in total. Drawn in a fine cartoon doodle style: a single thin, even-weight near-black pen line (#1A1A1A) with smooth confident curves, softly rounded ends and a slight hand-drawn wobble. The hand is puffy and marshmallow-soft: a plump rounded palm and exactly four chubby fingers in total (three fingers plus a thumb), every finger a soft bulbous shape with a rounded tip, with small overlapping knuckle bumps where fingers curl. Flat plain white fill inside every shape, no shading, no hatching, no gradients, no colour and no texture. The pose is springy and exaggerated with playful cartoon energy; interior detail is minimal, at most one or two short single-stroke lines for a crease. No fingernails, no skin tone, and the wrist is left open, its two contour lines simply trailing off with no closed stump. The whole drawing reads as a light, springy pen cartoon with real charm, NOT a thick marker doodle, NOT a realistic hand and NOT a clean geometric vector icon. Plain pure white background, the hand isolated and centred with generous padding, crisp and sharp. Match the attached sheet exactly: the same line weight, ink colour, finger proportions and hand-drawn character.",
      "rules": true
    },
    "R2C4 · Jazz spread": {
      "pre": "Attached as reference is a sheet of 25 hand-drawn cartoon hand poses in a 5 by 5 grid. Recreate exactly the hand at row 2, column 4, counting from the top left: an open hand raised from below, the fingers splayed wide apart in a lively jazz-hand spread. Reproduce that cell's pose, camera angle, finger curl and line character faithfully, as one single isolated hand, with one change: give the hand exactly four fingers in total. Drawn in a fine cartoon doodle style: a single thin, even-weight near-black pen line (#1A1A1A) with smooth confident curves, softly rounded ends and a slight hand-drawn wobble. The hand is puffy and marshmallow-soft: a plump rounded palm and exactly four chubby fingers in total (three fingers plus a thumb), every finger a soft bulbous shape with a rounded tip, with small overlapping knuckle bumps where fingers curl. Flat plain white fill inside every shape, no shading, no hatching, no gradients, no colour and no texture. The pose is springy and exaggerated with playful cartoon energy; interior detail is minimal, at most one or two short single-stroke lines for a crease. No fingernails, no skin tone, and the wrist is left open, its two contour lines simply trailing off with no closed stump. The whole drawing reads as a light, springy pen cartoon with real charm, NOT a thick marker doodle, NOT a realistic hand and NOT a clean geometric vector icon. Plain pure white background, the hand isolated and centred with generous padding, crisp and sharp. Match the attached sheet exactly: the same line weight, ink colour, finger proportions and hand-drawn character.",
      "rules": true
    },
    "R2C5 · Curl-back fist": {
      "pre": "Attached as reference is a sheet of 25 hand-drawn cartoon hand poses in a 5 by 5 grid. Recreate exactly the hand at row 2, column 5, counting from the top left: a hand seen from the back, the fingers curled tightly inward over the palm, knuckles forward, the thumb pressed across. Reproduce that cell's pose, camera angle, finger curl and line character faithfully, as one single isolated hand, with one change: give the hand exactly four fingers in total. Drawn in a fine cartoon doodle style: a single thin, even-weight near-black pen line (#1A1A1A) with smooth confident curves, softly rounded ends and a slight hand-drawn wobble. The hand is puffy and marshmallow-soft: a plump rounded palm and exactly four chubby fingers in total (three fingers plus a thumb), every finger a soft bulbous shape with a rounded tip, with small overlapping knuckle bumps where fingers curl. Flat plain white fill inside every shape, no shading, no hatching, no gradients, no colour and no texture. The pose is springy and exaggerated with playful cartoon energy; interior detail is minimal, at most one or two short single-stroke lines for a crease. No fingernails, no skin tone, and the wrist is left open, its two contour lines simply trailing off with no closed stump. The whole drawing reads as a light, springy pen cartoon with real charm, NOT a thick marker doodle, NOT a realistic hand and NOT a clean geometric vector icon. Plain pure white background, the hand isolated and centred with generous padding, crisp and sharp. Match the attached sheet exactly: the same line weight, ink colour, finger proportions and hand-drawn character.",
      "rules": true
    },
    "R3C1 · Point down": {
      "pre": "Attached as reference is a sheet of 25 hand-drawn cartoon hand poses in a 5 by 5 grid. Recreate exactly the hand at row 3, column 1, counting from the top left: a hand pointing straight down from above with the index finger, the other fingers curled up and away. Reproduce that cell's pose, camera angle, finger curl and line character faithfully, as one single isolated hand, with one change: give the hand exactly four fingers in total. Drawn in a fine cartoon doodle style: a single thin, even-weight near-black pen line (#1A1A1A) with smooth confident curves, softly rounded ends and a slight hand-drawn wobble. The hand is puffy and marshmallow-soft: a plump rounded palm and exactly four chubby fingers in total (three fingers plus a thumb), every finger a soft bulbous shape with a rounded tip, with small overlapping knuckle bumps where fingers curl. Flat plain white fill inside every shape, no shading, no hatching, no gradients, no colour and no texture. The pose is springy and exaggerated with playful cartoon energy; interior detail is minimal, at most one or two short single-stroke lines for a crease. No fingernails, no skin tone, and the wrist is left open, its two contour lines simply trailing off with no closed stump. The whole drawing reads as a light, springy pen cartoon with real charm, NOT a thick marker doodle, NOT a realistic hand and NOT a clean geometric vector icon. Plain pure white background, the hand isolated and centred with generous padding, crisp and sharp. Match the attached sheet exactly: the same line weight, ink colour, finger proportions and hand-drawn character.",
      "rules": true
    },
    "R3C2 · Two up": {
      "pre": "Attached as reference is a sheet of 25 hand-drawn cartoon hand poses in a 5 by 5 grid. Recreate exactly the hand at row 3, column 2, counting from the top left: a side-on hand raised from below with the index and middle fingers held straight up together, the rest folded. Reproduce that cell's pose, camera angle, finger curl and line character faithfully, as one single isolated hand, with one change: give the hand exactly four fingers in total. Drawn in a fine cartoon doodle style: a single thin, even-weight near-black pen line (#1A1A1A) with smooth confident curves, softly rounded ends and a slight hand-drawn wobble. The hand is puffy and marshmallow-soft: a plump rounded palm and exactly four chubby fingers in total (three fingers plus a thumb), every finger a soft bulbous shape with a rounded tip, with small overlapping knuckle bumps where fingers curl. Flat plain white fill inside every shape, no shading, no hatching, no gradients, no colour and no texture. The pose is springy and exaggerated with playful cartoon energy; interior detail is minimal, at most one or two short single-stroke lines for a crease. No fingernails, no skin tone, and the wrist is left open, its two contour lines simply trailing off with no closed stump. The whole drawing reads as a light, springy pen cartoon with real charm, NOT a thick marker doodle, NOT a realistic hand and NOT a clean geometric vector icon. Plain pure white background, the hand isolated and centred with generous padding, crisp and sharp. Match the attached sheet exactly: the same line weight, ink colour, finger proportions and hand-drawn character.",
      "rules": true
    },
    "R3C3 · Tiny pinch": {
      "pre": "Attached as reference is a sheet of 25 hand-drawn cartoon hand poses in a 5 by 5 grid. Recreate exactly the hand at row 3, column 3, counting from the top left: an upright hand from below, the thumb and index fingertip nearly touching as if holding something tiny, the other fingers softly curled. Reproduce that cell's pose, camera angle, finger curl and line character faithfully, as one single isolated hand, with one change: give the hand exactly four fingers in total. Drawn in a fine cartoon doodle style: a single thin, even-weight near-black pen line (#1A1A1A) with smooth confident curves, softly rounded ends and a slight hand-drawn wobble. The hand is puffy and marshmallow-soft: a plump rounded palm and exactly four chubby fingers in total (three fingers plus a thumb), every finger a soft bulbous shape with a rounded tip, with small overlapping knuckle bumps where fingers curl. Flat plain white fill inside every shape, no shading, no hatching, no gradients, no colour and no texture. The pose is springy and exaggerated with playful cartoon energy; interior detail is minimal, at most one or two short single-stroke lines for a crease. No fingernails, no skin tone, and the wrist is left open, its two contour lines simply trailing off with no closed stump. The whole drawing reads as a light, springy pen cartoon with real charm, NOT a thick marker doodle, NOT a realistic hand and NOT a clean geometric vector icon. Plain pure white background, the hand isolated and centred with generous padding, crisp and sharp. Match the attached sheet exactly: the same line weight, ink colour, finger proportions and hand-drawn character.",
      "rules": true
    },
    "R3C4 · Hover pat": {
      "pre": "Attached as reference is a sheet of 25 hand-drawn cartoon hand poses in a 5 by 5 grid. Recreate exactly the hand at row 3, column 4, counting from the top left: a flat palm-down hand gliding in from the upper left, fingers together, hovering as if patting or calming something. Reproduce that cell's pose, camera angle, finger curl and line character faithfully, as one single isolated hand, with one change: give the hand exactly four fingers in total. Drawn in a fine cartoon doodle style: a single thin, even-weight near-black pen line (#1A1A1A) with smooth confident curves, softly rounded ends and a slight hand-drawn wobble. The hand is puffy and marshmallow-soft: a plump rounded palm and exactly four chubby fingers in total (three fingers plus a thumb), every finger a soft bulbous shape with a rounded tip, with small overlapping knuckle bumps where fingers curl. Flat plain white fill inside every shape, no shading, no hatching, no gradients, no colour and no texture. The pose is springy and exaggerated with playful cartoon energy; interior detail is minimal, at most one or two short single-stroke lines for a crease. No fingernails, no skin tone, and the wrist is left open, its two contour lines simply trailing off with no closed stump. The whole drawing reads as a light, springy pen cartoon with real charm, NOT a thick marker doodle, NOT a realistic hand and NOT a clean geometric vector icon. Plain pure white background, the hand isolated and centred with generous padding, crisp and sharp. Match the attached sheet exactly: the same line weight, ink colour, finger proportions and hand-drawn character.",
      "rules": true
    },
    "R3C5 · Splay flat": {
      "pre": "Attached as reference is a sheet of 25 hand-drawn cartoon hand poses in a 5 by 5 grid. Recreate exactly the hand at row 3, column 5, counting from the top left: a sprawled palm-down hand arriving from the right, all fingers spread wide and flat. Reproduce that cell's pose, camera angle, finger curl and line character faithfully, as one single isolated hand, with one change: give the hand exactly four fingers in total. Drawn in a fine cartoon doodle style: a single thin, even-weight near-black pen line (#1A1A1A) with smooth confident curves, softly rounded ends and a slight hand-drawn wobble. The hand is puffy and marshmallow-soft: a plump rounded palm and exactly four chubby fingers in total (three fingers plus a thumb), every finger a soft bulbous shape with a rounded tip, with small overlapping knuckle bumps where fingers curl. Flat plain white fill inside every shape, no shading, no hatching, no gradients, no colour and no texture. The pose is springy and exaggerated with playful cartoon energy; interior detail is minimal, at most one or two short single-stroke lines for a crease. No fingernails, no skin tone, and the wrist is left open, its two contour lines simply trailing off with no closed stump. The whole drawing reads as a light, springy pen cartoon with real charm, NOT a thick marker doodle, NOT a realistic hand and NOT a clean geometric vector icon. Plain pure white background, the hand isolated and centred with generous padding, crisp and sharp. Match the attached sheet exactly: the same line weight, ink colour, finger proportions and hand-drawn character.",
      "rules": true
    },
    "R4C1 · Reach left": {
      "pre": "Attached as reference is a sheet of 25 hand-drawn cartoon hand poses in a 5 by 5 grid. Recreate exactly the hand at row 4, column 1, counting from the top left: a hand reaching left from the right edge, palm down, the fingers loosely extended as if about to pick something up. Reproduce that cell's pose, camera angle, finger curl and line character faithfully, as one single isolated hand, with one change: give the hand exactly four fingers in total. Drawn in a fine cartoon doodle style: a single thin, even-weight near-black pen line (#1A1A1A) with smooth confident curves, softly rounded ends and a slight hand-drawn wobble. The hand is puffy and marshmallow-soft: a plump rounded palm and exactly four chubby fingers in total (three fingers plus a thumb), every finger a soft bulbous shape with a rounded tip, with small overlapping knuckle bumps where fingers curl. Flat plain white fill inside every shape, no shading, no hatching, no gradients, no colour and no texture. The pose is springy and exaggerated with playful cartoon energy; interior detail is minimal, at most one or two short single-stroke lines for a crease. No fingernails, no skin tone, and the wrist is left open, its two contour lines simply trailing off with no closed stump. The whole drawing reads as a light, springy pen cartoon with real charm, NOT a thick marker doodle, NOT a realistic hand and NOT a clean geometric vector icon. Plain pure white background, the hand isolated and centred with generous padding, crisp and sharp. Match the attached sheet exactly: the same line weight, ink colour, finger proportions and hand-drawn character.",
      "rules": true
    },
    "R4C2 · Finger legs": {
      "pre": "Attached as reference is a sheet of 25 hand-drawn cartoon hand poses in a 5 by 5 grid. Recreate exactly the hand at row 4, column 2, counting from the top left: a relaxed hand hanging from above with two fingers split into a dangling V, like little legs mid-stroll. Reproduce that cell's pose, camera angle, finger curl and line character faithfully, as one single isolated hand, with one change: give the hand exactly four fingers in total. Drawn in a fine cartoon doodle style: a single thin, even-weight near-black pen line (#1A1A1A) with smooth confident curves, softly rounded ends and a slight hand-drawn wobble. The hand is puffy and marshmallow-soft: a plump rounded palm and exactly four chubby fingers in total (three fingers plus a thumb), every finger a soft bulbous shape with a rounded tip, with small overlapping knuckle bumps where fingers curl. Flat plain white fill inside every shape, no shading, no hatching, no gradients, no colour and no texture. The pose is springy and exaggerated with playful cartoon energy; interior detail is minimal, at most one or two short single-stroke lines for a crease. No fingernails, no skin tone, and the wrist is left open, its two contour lines simply trailing off with no closed stump. The whole drawing reads as a light, springy pen cartoon with real charm, NOT a thick marker doodle, NOT a realistic hand and NOT a clean geometric vector icon. Plain pure white background, the hand isolated and centred with generous padding, crisp and sharp. Match the attached sheet exactly: the same line weight, ink colour, finger proportions and hand-drawn character.",
      "rules": true
    },
    "R4C3 · Grip round": {
      "pre": "Attached as reference is a sheet of 25 hand-drawn cartoon hand poses in a 5 by 5 grid. Recreate exactly the hand at row 4, column 3, counting from the top left: a hand from below gripping a small round thing, the fingers curled around it and the thumb locking over the top. Reproduce that cell's pose, camera angle, finger curl and line character faithfully, as one single isolated hand, with one change: give the hand exactly four fingers in total. Drawn in a fine cartoon doodle style: a single thin, even-weight near-black pen line (#1A1A1A) with smooth confident curves, softly rounded ends and a slight hand-drawn wobble. The hand is puffy and marshmallow-soft: a plump rounded palm and exactly four chubby fingers in total (three fingers plus a thumb), every finger a soft bulbous shape with a rounded tip, with small overlapping knuckle bumps where fingers curl. Flat plain white fill inside every shape, no shading, no hatching, no gradients, no colour and no texture. The pose is springy and exaggerated with playful cartoon energy; interior detail is minimal, at most one or two short single-stroke lines for a crease. No fingernails, no skin tone, and the wrist is left open, its two contour lines simply trailing off with no closed stump. The whole drawing reads as a light, springy pen cartoon with real charm, NOT a thick marker doodle, NOT a realistic hand and NOT a clean geometric vector icon. Plain pure white background, the hand isolated and centred with generous padding, crisp and sharp. Match the attached sheet exactly: the same line weight, ink colour, finger proportions and hand-drawn character.",
      "rules": true
    },
    "R4C4 · Knock fist": {
      "pre": "Attached as reference is a sheet of 25 hand-drawn cartoon hand poses in a 5 by 5 grid. Recreate exactly the hand at row 4, column 4, counting from the top left: an upright loose fist from below, the fingers curled toward the viewer and the thumb wrapped across, as if about to knock. Reproduce that cell's pose, camera angle, finger curl and line character faithfully, as one single isolated hand, with one change: give the hand exactly four fingers in total. Drawn in a fine cartoon doodle style: a single thin, even-weight near-black pen line (#1A1A1A) with smooth confident curves, softly rounded ends and a slight hand-drawn wobble. The hand is puffy and marshmallow-soft: a plump rounded palm and exactly four chubby fingers in total (three fingers plus a thumb), every finger a soft bulbous shape with a rounded tip, with small overlapping knuckle bumps where fingers curl. Flat plain white fill inside every shape, no shading, no hatching, no gradients, no colour and no texture. The pose is springy and exaggerated with playful cartoon energy; interior detail is minimal, at most one or two short single-stroke lines for a crease. No fingernails, no skin tone, and the wrist is left open, its two contour lines simply trailing off with no closed stump. The whole drawing reads as a light, springy pen cartoon with real charm, NOT a thick marker doodle, NOT a realistic hand and NOT a clean geometric vector icon. Plain pure white background, the hand isolated and centred with generous padding, crisp and sharp. Match the attached sheet exactly: the same line weight, ink colour, finger proportions and hand-drawn character.",
      "rules": true
    },
    "R4C5 · Pencil write": {
      "pre": "Attached as reference is a sheet of 25 hand-drawn cartoon hand poses in a 5 by 5 grid. Recreate exactly the hand at row 4, column 5, counting from the top left: a hand holding a plain pencil in a writing grip, the tip touching down to the left as if mid-word. Reproduce that cell's pose, camera angle, finger curl and line character faithfully, as one single isolated hand, with one change: give the hand exactly four fingers in total. Drawn in a fine cartoon doodle style: a single thin, even-weight near-black pen line (#1A1A1A) with smooth confident curves, softly rounded ends and a slight hand-drawn wobble. The hand is puffy and marshmallow-soft: a plump rounded palm and exactly four chubby fingers in total (three fingers plus a thumb), every finger a soft bulbous shape with a rounded tip, with small overlapping knuckle bumps where fingers curl. Flat plain white fill inside every shape, no shading, no hatching, no gradients, no colour and no texture. The pose is springy and exaggerated with playful cartoon energy; interior detail is minimal, at most one or two short single-stroke lines for a crease. No fingernails, no skin tone, and the wrist is left open, its two contour lines simply trailing off with no closed stump. The whole drawing reads as a light, springy pen cartoon with real charm, NOT a thick marker doodle, NOT a realistic hand and NOT a clean geometric vector icon. Plain pure white background, the hand isolated and centred with generous padding, crisp and sharp. Match the attached sheet exactly: the same line weight, ink colour, finger proportions and hand-drawn character.",
      "rules": true
    },
    "R5C1 · Squeeze fist": {
      "pre": "Attached as reference is a sheet of 25 hand-drawn cartoon hand poses in a 5 by 5 grid. Recreate exactly the hand at row 5, column 1, counting from the top left: a side-on squeezing fist arriving from the left, the fingers clenched hard around themselves. Reproduce that cell's pose, camera angle, finger curl and line character faithfully, as one single isolated hand, with one change: give the hand exactly four fingers in total. Drawn in a fine cartoon doodle style: a single thin, even-weight near-black pen line (#1A1A1A) with smooth confident curves, softly rounded ends and a slight hand-drawn wobble. The hand is puffy and marshmallow-soft: a plump rounded palm and exactly four chubby fingers in total (three fingers plus a thumb), every finger a soft bulbous shape with a rounded tip, with small overlapping knuckle bumps where fingers curl. Flat plain white fill inside every shape, no shading, no hatching, no gradients, no colour and no texture. The pose is springy and exaggerated with playful cartoon energy; interior detail is minimal, at most one or two short single-stroke lines for a crease. No fingernails, no skin tone, and the wrist is left open, its two contour lines simply trailing off with no closed stump. The whole drawing reads as a light, springy pen cartoon with real charm, NOT a thick marker doodle, NOT a realistic hand and NOT a clean geometric vector icon. Plain pure white background, the hand isolated and centred with generous padding, crisp and sharp. Match the attached sheet exactly: the same line weight, ink colour, finger proportions and hand-drawn character.",
      "rules": true
    },
    "R5C2 · Finger gun": {
      "pre": "Attached as reference is a sheet of 25 hand-drawn cartoon hand poses in a 5 by 5 grid. Recreate exactly the hand at row 5, column 2, counting from the top left: a hand from below with the index finger flicked up and out and the thumb raised, the other fingers folded, like a casual finger-gun aimed upward. Reproduce that cell's pose, camera angle, finger curl and line character faithfully, as one single isolated hand, with one change: give the hand exactly four fingers in total. Drawn in a fine cartoon doodle style: a single thin, even-weight near-black pen line (#1A1A1A) with smooth confident curves, softly rounded ends and a slight hand-drawn wobble. The hand is puffy and marshmallow-soft: a plump rounded palm and exactly four chubby fingers in total (three fingers plus a thumb), every finger a soft bulbous shape with a rounded tip, with small overlapping knuckle bumps where fingers curl. Flat plain white fill inside every shape, no shading, no hatching, no gradients, no colour and no texture. The pose is springy and exaggerated with playful cartoon energy; interior detail is minimal, at most one or two short single-stroke lines for a crease. No fingernails, no skin tone, and the wrist is left open, its two contour lines simply trailing off with no closed stump. The whole drawing reads as a light, springy pen cartoon with real charm, NOT a thick marker doodle, NOT a realistic hand and NOT a clean geometric vector icon. Plain pure white background, the hand isolated and centred with generous padding, crisp and sharp. Match the attached sheet exactly: the same line weight, ink colour, finger proportions and hand-drawn character.",
      "rules": true
    },
    "R5C3 · OK tilt": {
      "pre": "Attached as reference is a sheet of 25 hand-drawn cartoon hand poses in a 5 by 5 grid. Recreate exactly the hand at row 5, column 3, counting from the top left: a tilted OK-style pinch from the lower right, the thumb and index finger closed in a ring and the other fingers curled back. Reproduce that cell's pose, camera angle, finger curl and line character faithfully, as one single isolated hand, with one change: give the hand exactly four fingers in total. Drawn in a fine cartoon doodle style: a single thin, even-weight near-black pen line (#1A1A1A) with smooth confident curves, softly rounded ends and a slight hand-drawn wobble. The hand is puffy and marshmallow-soft: a plump rounded palm and exactly four chubby fingers in total (three fingers plus a thumb), every finger a soft bulbous shape with a rounded tip, with small overlapping knuckle bumps where fingers curl. Flat plain white fill inside every shape, no shading, no hatching, no gradients, no colour and no texture. The pose is springy and exaggerated with playful cartoon energy; interior detail is minimal, at most one or two short single-stroke lines for a crease. No fingernails, no skin tone, and the wrist is left open, its two contour lines simply trailing off with no closed stump. The whole drawing reads as a light, springy pen cartoon with real charm, NOT a thick marker doodle, NOT a realistic hand and NOT a clean geometric vector icon. Plain pure white background, the hand isolated and centred with generous padding, crisp and sharp. Match the attached sheet exactly: the same line weight, ink colour, finger proportions and hand-drawn character.",
      "rules": true
    },
    "R5C4 · Rock horns": {
      "pre": "Attached as reference is a sheet of 25 hand-drawn cartoon hand poses in a 5 by 5 grid. Recreate exactly the hand at row 5, column 4, counting from the top left: a hand from below throwing a rock-on sign, the index and outermost finger raised in horns with the middle finger folded under the thumb. Reproduce that cell's pose, camera angle, finger curl and line character faithfully, as one single isolated hand, with one change: give the hand exactly four fingers in total. Drawn in a fine cartoon doodle style: a single thin, even-weight near-black pen line (#1A1A1A) with smooth confident curves, softly rounded ends and a slight hand-drawn wobble. The hand is puffy and marshmallow-soft: a plump rounded palm and exactly four chubby fingers in total (three fingers plus a thumb), every finger a soft bulbous shape with a rounded tip, with small overlapping knuckle bumps where fingers curl. Flat plain white fill inside every shape, no shading, no hatching, no gradients, no colour and no texture. The pose is springy and exaggerated with playful cartoon energy; interior detail is minimal, at most one or two short single-stroke lines for a crease. No fingernails, no skin tone, and the wrist is left open, its two contour lines simply trailing off with no closed stump. The whole drawing reads as a light, springy pen cartoon with real charm, NOT a thick marker doodle, NOT a realistic hand and NOT a clean geometric vector icon. Plain pure white background, the hand isolated and centred with generous padding, crisp and sharp. Match the attached sheet exactly: the same line weight, ink colour, finger proportions and hand-drawn character.",
      "rules": true
    },
    "R5C5 · Drop token": {
      "pre": "Attached as reference is a sheet of 25 hand-drawn cartoon hand poses in a 5 by 5 grid. Recreate exactly the hand at row 5, column 5, counting from the top left: a hand reaching down from the upper right, pinching a small round token between thumb and fingertip as if about to drop it. Reproduce that cell's pose, camera angle, finger curl and line character faithfully, as one single isolated hand, with one change: give the hand exactly four fingers in total. Drawn in a fine cartoon doodle style: a single thin, even-weight near-black pen line (#1A1A1A) with smooth confident curves, softly rounded ends and a slight hand-drawn wobble. The hand is puffy and marshmallow-soft: a plump rounded palm and exactly four chubby fingers in total (three fingers plus a thumb), every finger a soft bulbous shape with a rounded tip, with small overlapping knuckle bumps where fingers curl. Flat plain white fill inside every shape, no shading, no hatching, no gradients, no colour and no texture. The pose is springy and exaggerated with playful cartoon energy; interior detail is minimal, at most one or two short single-stroke lines for a crease. No fingernails, no skin tone, and the wrist is left open, its two contour lines simply trailing off with no closed stump. The whole drawing reads as a light, springy pen cartoon with real charm, NOT a thick marker doodle, NOT a realistic hand and NOT a clean geometric vector icon. Plain pure white background, the hand isolated and centred with generous padding, crisp and sharp. Match the attached sheet exactly: the same line weight, ink colour, finger proportions and hand-drawn character.",
      "rules": true
    }
  },
  {
    "id": "pl-hands-signals",
    "group": "Doodle hands",
    "eyebrow": "Hands",
    "title": "Gestures · signals",
    "summary": "Six signalling hands, copy-paste ready: point, thumbs up, wave, peace, OK, fist bump. Attach the hands reference sheet for an exact style match.",
    "Pointing": {
      "pre": "A hand-drawn doodle illustration of a single cartoon hand pointing to the right, the index finger extended straight, the other two chubby fingers curled into the palm and the thumb resting along the top. Drawn in a fine cartoon doodle style: a single thin, even-weight near-black pen line (#1A1A1A) with smooth confident curves, softly rounded ends and a slight hand-drawn wobble. The hand is puffy and marshmallow-soft: a plump rounded palm and exactly four chubby fingers in total (three fingers plus a thumb), every finger a soft bulbous shape with a rounded tip, with small overlapping knuckle bumps where fingers curl. Flat plain white fill inside every shape, no shading, no hatching, no gradients, no colour and no texture. The pose is springy and exaggerated with playful cartoon energy; interior detail is minimal, at most one or two short single-stroke lines for a crease. No fingernails, no skin tone, and the wrist is left open, its two contour lines simply trailing off with no closed stump. The whole drawing reads as a light, springy pen cartoon with real charm, NOT a thick marker doodle, NOT a realistic hand and NOT a clean geometric vector icon. Plain pure white background, the hand isolated and centred with generous padding, crisp and sharp. If the reference hands sheet is attached, match its exact line weight, ink colour, finger proportions and hand-drawn character.",
      "rules": true
    },
    "Thumbs up": {
      "pre": "A hand-drawn doodle illustration of a single cartoon hand giving a confident thumbs up, the fingers curled into a soft rounded fist and the thumb standing straight up. Drawn in a fine cartoon doodle style: a single thin, even-weight near-black pen line (#1A1A1A) with smooth confident curves, softly rounded ends and a slight hand-drawn wobble. The hand is puffy and marshmallow-soft: a plump rounded palm and exactly four chubby fingers in total (three fingers plus a thumb), every finger a soft bulbous shape with a rounded tip, with small overlapping knuckle bumps where fingers curl. Flat plain white fill inside every shape, no shading, no hatching, no gradients, no colour and no texture. The pose is springy and exaggerated with playful cartoon energy; interior detail is minimal, at most one or two short single-stroke lines for a crease. No fingernails, no skin tone, and the wrist is left open, its two contour lines simply trailing off with no closed stump. The whole drawing reads as a light, springy pen cartoon with real charm, NOT a thick marker doodle, NOT a realistic hand and NOT a clean geometric vector icon. Plain pure white background, the hand isolated and centred with generous padding, crisp and sharp. If the reference hands sheet is attached, match its exact line weight, ink colour, finger proportions and hand-drawn character.",
      "rules": true
    },
    "Wave": {
      "pre": "A hand-drawn doodle illustration of a single cartoon hand waving hello, the open palm facing forward with all four chubby fingers gently spread, and two short curved motion strokes beside it drawn in the same ink. Drawn in a fine cartoon doodle style: a single thin, even-weight near-black pen line (#1A1A1A) with smooth confident curves, softly rounded ends and a slight hand-drawn wobble. The hand is puffy and marshmallow-soft: a plump rounded palm and exactly four chubby fingers in total (three fingers plus a thumb), every finger a soft bulbous shape with a rounded tip, with small overlapping knuckle bumps where fingers curl. Flat plain white fill inside every shape, no shading, no hatching, no gradients, no colour and no texture. The pose is springy and exaggerated with playful cartoon energy; interior detail is minimal, at most one or two short single-stroke lines for a crease. No fingernails, no skin tone, and the wrist is left open, its two contour lines simply trailing off with no closed stump. The whole drawing reads as a light, springy pen cartoon with real charm, NOT a thick marker doodle, NOT a realistic hand and NOT a clean geometric vector icon. Plain pure white background, the hand isolated and centred with generous padding, crisp and sharp. If the reference hands sheet is attached, match its exact line weight, ink colour, finger proportions and hand-drawn character.",
      "rules": true
    },
    "Peace": {
      "pre": "A hand-drawn doodle illustration of a single cartoon hand making a peace sign, the index and middle fingers raised in a wide V, the remaining finger folded down with the thumb resting across it. Drawn in a fine cartoon doodle style: a single thin, even-weight near-black pen line (#1A1A1A) with smooth confident curves, softly rounded ends and a slight hand-drawn wobble. The hand is puffy and marshmallow-soft: a plump rounded palm and exactly four chubby fingers in total (three fingers plus a thumb), every finger a soft bulbous shape with a rounded tip, with small overlapping knuckle bumps where fingers curl. Flat plain white fill inside every shape, no shading, no hatching, no gradients, no colour and no texture. The pose is springy and exaggerated with playful cartoon energy; interior detail is minimal, at most one or two short single-stroke lines for a crease. No fingernails, no skin tone, and the wrist is left open, its two contour lines simply trailing off with no closed stump. The whole drawing reads as a light, springy pen cartoon with real charm, NOT a thick marker doodle, NOT a realistic hand and NOT a clean geometric vector icon. Plain pure white background, the hand isolated and centred with generous padding, crisp and sharp. If the reference hands sheet is attached, match its exact line weight, ink colour, finger proportions and hand-drawn character.",
      "rules": true
    },
    "OK": {
      "pre": "A hand-drawn doodle illustration of a single cartoon hand making an OK sign, the thumb and index finger touching in a round ring, the other two chubby fingers relaxed and fanned upward. Drawn in a fine cartoon doodle style: a single thin, even-weight near-black pen line (#1A1A1A) with smooth confident curves, softly rounded ends and a slight hand-drawn wobble. The hand is puffy and marshmallow-soft: a plump rounded palm and exactly four chubby fingers in total (three fingers plus a thumb), every finger a soft bulbous shape with a rounded tip, with small overlapping knuckle bumps where fingers curl. Flat plain white fill inside every shape, no shading, no hatching, no gradients, no colour and no texture. The pose is springy and exaggerated with playful cartoon energy; interior detail is minimal, at most one or two short single-stroke lines for a crease. No fingernails, no skin tone, and the wrist is left open, its two contour lines simply trailing off with no closed stump. The whole drawing reads as a light, springy pen cartoon with real charm, NOT a thick marker doodle, NOT a realistic hand and NOT a clean geometric vector icon. Plain pure white background, the hand isolated and centred with generous padding, crisp and sharp. If the reference hands sheet is attached, match its exact line weight, ink colour, finger proportions and hand-drawn character.",
      "rules": true
    },
    "Fist bump": {
      "pre": "A hand-drawn doodle illustration of a single cartoon fist held out sideways for a fist bump, the knuckles facing right, with two short straight impact strokes just beyond the knuckles drawn in the same ink. Drawn in a fine cartoon doodle style: a single thin, even-weight near-black pen line (#1A1A1A) with smooth confident curves, softly rounded ends and a slight hand-drawn wobble. The hand is puffy and marshmallow-soft: a plump rounded palm and exactly four chubby fingers in total (three fingers plus a thumb), every finger a soft bulbous shape with a rounded tip, with small overlapping knuckle bumps where fingers curl. Flat plain white fill inside every shape, no shading, no hatching, no gradients, no colour and no texture. The pose is springy and exaggerated with playful cartoon energy; interior detail is minimal, at most one or two short single-stroke lines for a crease. No fingernails, no skin tone, and the wrist is left open, its two contour lines simply trailing off with no closed stump. The whole drawing reads as a light, springy pen cartoon with real charm, NOT a thick marker doodle, NOT a realistic hand and NOT a clean geometric vector icon. Plain pure white background, the hand isolated and centred with generous padding, crisp and sharp. If the reference hands sheet is attached, match its exact line weight, ink colour, finger proportions and hand-drawn character.",
      "rules": true
    }
  },
  {
    "id": "pl-hands-actions",
    "group": "Doodle hands",
    "eyebrow": "Hands",
    "title": "Gestures · actions",
    "summary": "Six doing hands, copy-paste ready: holding a phone, tapping, writing, holding a mug, pinching a token, clapping. Props are drawn in the same single-outline doodle style.",
    "Holding a phone": {
      "pre": "A hand-drawn doodle illustration of a single cartoon hand holding up a simple smartphone with a completely blank empty screen, the thumb wrapped around one edge; the phone is drawn in the same doodle outline with a plain white screen. Drawn in a fine cartoon doodle style: a single thin, even-weight near-black pen line (#1A1A1A) with smooth confident curves, softly rounded ends and a slight hand-drawn wobble. The hand is puffy and marshmallow-soft: a plump rounded palm and exactly four chubby fingers in total (three fingers plus a thumb), every finger a soft bulbous shape with a rounded tip, with small overlapping knuckle bumps where fingers curl. Flat plain white fill inside every shape, no shading, no hatching, no gradients, no colour and no texture. The pose is springy and exaggerated with playful cartoon energy; interior detail is minimal, at most one or two short single-stroke lines for a crease. No fingernails, no skin tone, and the wrist is left open, its two contour lines simply trailing off with no closed stump. The whole drawing reads as a light, springy pen cartoon with real charm, NOT a thick marker doodle, NOT a realistic hand and NOT a clean geometric vector icon. Plain pure white background, the hand isolated and centred with generous padding, crisp and sharp. If the reference hands sheet is attached, match its exact line weight, ink colour, finger proportions and hand-drawn character.",
      "rules": true
    },
    "Tap": {
      "pre": "A hand-drawn doodle illustration of a single cartoon hand tapping, the index finger extended downward at an angle with the other fingers softly curled, and two short straight tap strokes just above the fingertip drawn in the same ink. Drawn in a fine cartoon doodle style: a single thin, even-weight near-black pen line (#1A1A1A) with smooth confident curves, softly rounded ends and a slight hand-drawn wobble. The hand is puffy and marshmallow-soft: a plump rounded palm and exactly four chubby fingers in total (three fingers plus a thumb), every finger a soft bulbous shape with a rounded tip, with small overlapping knuckle bumps where fingers curl. Flat plain white fill inside every shape, no shading, no hatching, no gradients, no colour and no texture. The pose is springy and exaggerated with playful cartoon energy; interior detail is minimal, at most one or two short single-stroke lines for a crease. No fingernails, no skin tone, and the wrist is left open, its two contour lines simply trailing off with no closed stump. The whole drawing reads as a light, springy pen cartoon with real charm, NOT a thick marker doodle, NOT a realistic hand and NOT a clean geometric vector icon. Plain pure white background, the hand isolated and centred with generous padding, crisp and sharp. If the reference hands sheet is attached, match its exact line weight, ink colour, finger proportions and hand-drawn character.",
      "rules": true
    },
    "Writing": {
      "pre": "A hand-drawn doodle illustration of a single cartoon hand holding a plain pencil in a natural writing grip, the tip touching down as if mid-sentence; the pencil is drawn in the same doodle outline and no writing appears anywhere. Drawn in a fine cartoon doodle style: a single thin, even-weight near-black pen line (#1A1A1A) with smooth confident curves, softly rounded ends and a slight hand-drawn wobble. The hand is puffy and marshmallow-soft: a plump rounded palm and exactly four chubby fingers in total (three fingers plus a thumb), every finger a soft bulbous shape with a rounded tip, with small overlapping knuckle bumps where fingers curl. Flat plain white fill inside every shape, no shading, no hatching, no gradients, no colour and no texture. The pose is springy and exaggerated with playful cartoon energy; interior detail is minimal, at most one or two short single-stroke lines for a crease. No fingernails, no skin tone, and the wrist is left open, its two contour lines simply trailing off with no closed stump. The whole drawing reads as a light, springy pen cartoon with real charm, NOT a thick marker doodle, NOT a realistic hand and NOT a clean geometric vector icon. Plain pure white background, the hand isolated and centred with generous padding, crisp and sharp. If the reference hands sheet is attached, match its exact line weight, ink colour, finger proportions and hand-drawn character.",
      "rules": true
    },
    "Coffee mug": {
      "pre": "A hand-drawn doodle illustration of a single cartoon hand holding a simple round coffee mug by its handle, one soft wavy steam line rising from the rim, the mug drawn in the same doodle outline with a plain white fill. Drawn in a fine cartoon doodle style: a single thin, even-weight near-black pen line (#1A1A1A) with smooth confident curves, softly rounded ends and a slight hand-drawn wobble. The hand is puffy and marshmallow-soft: a plump rounded palm and exactly four chubby fingers in total (three fingers plus a thumb), every finger a soft bulbous shape with a rounded tip, with small overlapping knuckle bumps where fingers curl. Flat plain white fill inside every shape, no shading, no hatching, no gradients, no colour and no texture. The pose is springy and exaggerated with playful cartoon energy; interior detail is minimal, at most one or two short single-stroke lines for a crease. No fingernails, no skin tone, and the wrist is left open, its two contour lines simply trailing off with no closed stump. The whole drawing reads as a light, springy pen cartoon with real charm, NOT a thick marker doodle, NOT a realistic hand and NOT a clean geometric vector icon. Plain pure white background, the hand isolated and centred with generous padding, crisp and sharp. If the reference hands sheet is attached, match its exact line weight, ink colour, finger proportions and hand-drawn character.",
      "rules": true
    },
    "Pinch": {
      "pre": "A hand-drawn doodle illustration of a single cartoon hand pinching a small round token between thumb and index finger, holding it up as if showing it off, the other fingers gently curled. Drawn in a fine cartoon doodle style: a single thin, even-weight near-black pen line (#1A1A1A) with smooth confident curves, softly rounded ends and a slight hand-drawn wobble. The hand is puffy and marshmallow-soft: a plump rounded palm and exactly four chubby fingers in total (three fingers plus a thumb), every finger a soft bulbous shape with a rounded tip, with small overlapping knuckle bumps where fingers curl. Flat plain white fill inside every shape, no shading, no hatching, no gradients, no colour and no texture. The pose is springy and exaggerated with playful cartoon energy; interior detail is minimal, at most one or two short single-stroke lines for a crease. No fingernails, no skin tone, and the wrist is left open, its two contour lines simply trailing off with no closed stump. The whole drawing reads as a light, springy pen cartoon with real charm, NOT a thick marker doodle, NOT a realistic hand and NOT a clean geometric vector icon. Plain pure white background, the hand isolated and centred with generous padding, crisp and sharp. If the reference hands sheet is attached, match its exact line weight, ink colour, finger proportions and hand-drawn character.",
      "rules": true
    },
    "Clap (pair)": {
      "pre": "A hand-drawn doodle illustration of a pair of cartoon hands mid-clap, the palms meeting at a slight angle, with three short straight burst strokes around the point of contact drawn in the same ink. Drawn in a fine cartoon doodle style: a single thin, even-weight near-black pen line (#1A1A1A) with smooth confident curves, softly rounded ends and a slight hand-drawn wobble. The hand is puffy and marshmallow-soft: a plump rounded palm and exactly four chubby fingers in total (three fingers plus a thumb), every finger a soft bulbous shape with a rounded tip, with small overlapping knuckle bumps where fingers curl. Flat plain white fill inside every shape, no shading, no hatching, no gradients, no colour and no texture. The pose is springy and exaggerated with playful cartoon energy; interior detail is minimal, at most one or two short single-stroke lines for a crease. No fingernails, no skin tone, and each wrist is left open, its contour lines simply trailing off with no closed stump. The whole drawing reads as a light, springy pen cartoon with real charm, NOT a thick marker doodle, NOT realistic hands and NOT a clean geometric vector icon. Plain pure white background, the hands isolated and centred with generous padding, crisp and sharp. If the reference hands sheet is attached, match its exact line weight, ink colour, finger proportions and hand-drawn character.",
      "rules": true
    }
  }
];
