// Image-generation prompts: Schedule images. The PROSE half of the group. Every
// copy-paste block, the scene catalog and the template are composed from the
// recipe in ./scheduleImagesViews.js by ./scheduleImages.js, so nothing here is a
// frozen prompt. Part of the prompt library (src/prd/promptLibrary).

export const SPECS = [
  {
    id: "pl-schedule-images-system",
    group: "Schedule images",
    eyebrow: "Zepto",
    title: "Schedule images · the system",
    summary:
      "Faceless candid stills of the moment someone in India would schedule a grocery delivery: on the back under a block-print razai with the other side of the bed empty, at the open door of a Mumbai local, on the rooftop parapet at blue hour with a second chai glass waiting, cross-legged on the mosaic floor against the almirah. Two looks: Indian colour documentary (the default, lit only by what is in the room, each source its own colour, 35mm and everything in focus, the room bringing the colour) and the campaign hard sun. Curious camera angles, a person present through hands and clothes and never a face, a phone in a brand-colour case with its screen left blank for the app UI in Figma. Grew out of the phone-in-hand tile of Zepto campaign tiles on 2026-08-16; the scenes were rewritten as Indian frames with a beat, and the light moved into a Look dial, on 2026-09-04.",
    "What this is": [
      "A system for the scheduled-delivery campaign's photographic layer: the moment of ordering ahead, not the goods arriving. By default no scene carries groceries, because the goods are not there yet, which is the point; the Objects dial can place up to six items from the assortment as the goods from the last order, props never subjects.",
      "Written to a six-frame phone-in-hand moodboard (fintech and streaming campaign stills): POV down the body on a leopard throw; a hoodie torso laughing at a pink-cased phone with the face cut by the top edge; over the shoulder onto a phone in both hands over khakis and a canvas bag; lying on the back in a blue hoodie shot from above, the face at the frame edge; two friends from below against the sky, faces cut; a bomber-jacket torso in a metro concourse holding a blue phone sideways, head cut at the chin.",
      "What recurs in the board, and what this system fixes: no face carries the frame; the person is present through hands, posture and clothes; the phone is small in frame and wears a coloured case; everyday rooms keep their clutter; a soft muted 35mm film grade; the camera is somewhere a snapshot would not be.",
      "Built on the shared recipe contract (image/recipe.js), like 3D faces and the campaign tiles: adding a scene or an angle is one entry in scheduleImagesViews.js and it appears in the picker, the written-out catalog and the template at once.",
    ],
    "The constant": [
      "No face, stated positively: the head kept out of frame, cut by the frame edge above the chin or turned away. Faces are the model's most exposed failure (waxy skin, symmetric features) and the board never leans on one, so the system does not either.",
      "The phone, from real outputs that always rendered it wrong (2026-09-04): a slab the shape of an iPhone Pro Max in a matte case in the colorway, its screen FACING THE CAMERA, switched off and plain black (the first outputs came back with the phone reversed because the clause said dark glass reflecting the room and a hand round its back, which reads as the back glass), held in one hand with the thumb along the edge, the person looking down at it and not at the camera; the UI is composited over the black screen in Figma, which is how real screen-replacement plates are shot. No hex codes anywhere: neither vendor documents them and a text hex measured twelve times worse than a swatch. The earlier lit brand field stays as the second Phone option.",
      "Frame density, from the same outputs: every frame is one subject and action, the phone hold, one place cue and one beat object, at most five named things. Both vendors structure a prompt as one subject, one action, one place and say iterate rather than overload; the practitioner band is three to five. POV down the body and true overhead are the two angles with failure evidence, so no scene uses them as its own camera and the picker flags them.",
      "Every scene is built on Agam's Airbnb framework, the Away icon system's rule after the Airbnb service-icon set (2026-09-04, after outputs that had no semblance to real life): work backward from the viewer and lead with the single most universally recognised cue for the moment (in bed at night, holding the pole in a crowded train, a rooftop at dusk, a shop shutter down), then at most two supporting props, which is where India lives (a steel tumbler, a cloth bag, the grill), a bold simple silhouette with space around it, no clutter. A recognisability clause states the rule in every prompt.",
      "Every scene is a frame with a place and a beat. The place is named by its real surfaces (a mosaic floor with brass strips, a distemper wall, an olive steel almirah, a black mild-steel grill, a bare tube light, the wood-finish seats of a Mumbai local, a kirana's pulled-down shutter). The beat is never a feeling word: it is one unplanted detail stated as inventory, a rinsed empty milk pouch upside down on the rack, a second chai glass on the parapet, one diya already lit to test the wick, the steel plates counted out. A labelled feeling is what Barthes calls the studium; the small plain object is the punctum.",
      "One fixed clause order: use, reference, camera, frame, no-face, phone, objects, light system, source, lens, finish, rules. Consistent order is what makes a set of prompts diffable when one scene drifts.",
      "What is NOT constant any more (2026-09-04): the light system, the lens, the grain and the palette. Those were the campaign crate's packshot rules (100mm, no grain, one hard sun, no fill, the room kept muted) bolted onto lifestyle stills, and they were why the stills read dead. They now live in the Look dial.",
    ],
    "Two settings": [
      "PEOPLE: who is in the frame and how. Scene (the moment: posture, clothes, room, camera, light source, lens), Angle (the camera position, scene's own or one of twelve), People (one person; two people as a second hand at the phone; with a child, a small hand reaching in; hands only; or Objects only, which swaps the Scene row for object scenes). Scenes never carry goods or a people count, so nothing here overlaps the other setting.",
      "OBJECT: what is in the frame besides the person. Case colour (the phone's case wears the colorway, its screen is the contrasting blank brand field) and Objects (up to six from the assortment, placed where the scene keeps them). These are the only things in the frame that carry brand colour or product; the room and clothes keep their own tones.",
      "Reference and Length sit outside both: how the prompt is delivered, not what is in the picture.",
    ],
    "The dials": [
      "Look: Indian colour documentary (the default) or Campaign hard sun. The documentary look is lit only by the sources visible in the frame, each left its own colour and none corrected to the other (a tube light with its green cast left in, a warm bulb, a street lamp through a grill; the phone screen is off and lights nothing), one source the brightest thing at night and the room a stop or two darker than the street by day; shot like a 35mm film photograph on a 35mm lens with everything in focus so colour carries the eye across one plane, subtle grain, natural colour balance; colour placed not poured, the room bringing it as its own surfaces with one or two colour rhymes and one saturated accent on an ordinary object; brand colour on the phone alone; nothing added to signal India. The hard-sun look is the campaign tiles' recipe on the same scenes, reading each scene's hard-source clause instead of its documentary one. Object stills always compose in the campaign look.",
      "Time of day: a scalable light layer. Each scene names the portal where daylight enters (the balcony door, the kitchen window grill, the open doorway, the open sky) and which conditions fit it; the dial supplies the sky condition, Bright day (the default, mid-morning sun in one crisp patch, pale walls bouncing it back, the room lit and airy, like the campaign's other assets), Golden hour, Monsoon overcast, Blue hour; Night and every night-only scene fall through to the scene's own fixtures. The two travel scenes carry their journey's light and skip the dial.",
      "Shuffle: rolls people, angle, objects, case colour and time of day inside what the scene allows, leaning off the scene's own camera, keeping POV and overhead for when a reference is attached, never more than two objects.",
      "Journey: seven recognisable people, each a whole person (Priya on the local, the case's own commuter; the metro rider in a PG room; the auto to an older flat; the office cab to a new-build flat; the scooter pillion to a two-room flat; the red city bus to a shared flat; the parent on the morning school run to a family flat with toys on the floor). One pick changes every scene: the Commute home hero cue, the ride home with luggage, the home in every domestic scene, the clothes, what they carry, and what waits at the kerb outside the shut shop. The case's other two personas are scenes rather than journeys: the coverage-edge regular is Store closed, the weekly-shop planner is Sunday grocery planning.",
      "Phone: Black screen facing camera (default) or Lit brand field. Both name the hand-device contact as a physical relation and put the phone second after the frame, because the first elements carry more weight.",
      "Scene: twenty moments (2026-09-07: family lunch, store down and back in fifteen, back-to-back meetings, peak hour stuck in traffic, a gift for someone), the first fifteen: each with its own camera position, frame, light source, lens and a place where objects sit. Late night in bed (phone face plus a shaded bedside lamp); Commute home (metro concourse, diffused ceiling panels, one warm exit-sign accent); Planning a party (a rooftop terrace from below, the whole sky as the source; set People to two for the friend); Sunday grocery planning (kitchen floor against the cabinets, a big side window through a sheer); Office end of day (sofa by steel windows, fading daylight plus a warm lamp); Morning kitchen counter (forearms on the counter, one north window); Guests tomorrow (POV on the sofa on a leopard throw, a shaded floor lamp); Packing for tomorrow (counter late, a warm under-cabinet strip); After the workout (floor against the wall, a big window down the hall); Festival prep (floor of marigolds and diyas from above, an open doorway); Rainy evening (window seat, the whole rain-grey window); Balcony at first light (rail, the whole early sky); Planning ahead for morning (kitchen table at night with tomorrow laid out, one shaded pendant); Timing it for arrival (back seat of a cab from the airport, the passing city as the light); Store closed, order for later (a torso before a pulled-down shutter, one streetlamp softened by damp air).",
      "Object groups: named trios for the moments people schedule for (breakfast, chai time, snacks, dinner, fresh produce, fruit, weekly staples, fridge restock, South Indian breakfast, kids' tiffin, party planning, birthday, festival, puja, baking, late night, sick day, baby, pet, cleaning day, rainy evening, guests tomorrow); picking one sets the three objects at once, and the trio can then be edited.",
      "Objects: up to six from a scheduled-delivery assortment of fifty-one (dairy and breakfast: milk, bread, eggs, curd, butter, cheese, ghee, cereal, coffee, juice; produce: bananas, mangoes, tomatoes, coriander, onions, potatoes, apples, grapes, lemons, green chillies; staples: atta, rice, dal, idli batter, paneer, water; treats: ice cream, chocolate, biscuits, snacks, cold drinks, samosas, frozen momos, tender coconut, cutting chai, cake, ice; home and care: diapers, baby food, sanitary pads, toilet paper, dish soap, detergent, pet food, a medicine strip; occasion: flowers, marigold string, incense, candles, balloons, a tiffin box), each a shape-only cue so it survives any scene, placed where the scene keeps them (the bedside table, a kraft bag on the wrist, the counter, the sill). Pack faces stay blank per the group rule.",
      "People: one person (default); two people, stated as exactly two with a second hand pointing at the phone; with a child, a small hand reaching in while the adult holds the phone; hands only, the body cropped out; or Objects only: nobody and no phone, and the Scene row switches to OBJECT SCENES that stage the goods on their own: four stagings borrowed from the campaign group (crate on the sweep, colour-field packshot, edge-to-edge wall, corner peek) and four domestic ones (doorstep bag, fridge shelf, table flat lay, tote on the floor), ALL in this system's one register (hard sun with the scene naming where it enters, 100mm lens, same Style clause, same opener) so object stills and people stills read as one shoot. The colorway goes on the manufactured brand surface (crate, sweep, field, delivery bag). Faces stay out in every case; the count is said out loud because neither vendor documents hand-count control.",
      "Angle: the scene's own camera, or one of twelve positions that override it: six from the board (POV down the body, over the shoulder, from below, overhead, torso at eye level, low beside) and six more curious ones (tilted fifteen degrees, through a soft foreground, in a dark-window reflection, knee level from the side, from directly behind, wide with the person small in the room). Each keeps the face out.",
      "Colorway: which brand colour the phone case wears; the screen takes the contrasting brand field.",
      "Reference: words only; a real moodboard photograph attached for its photographic quality only (skin texture, grain, grade, contrast, framing, take none of its content), which is the strongest documented lever against plastic skin; or an anchor render from the set. The style clause (labelled Style:) is present in every prompt regardless of reference mode; with a real photo attached only the skin words drop, since the photo carries skin texture.",
      "Length: compact, the default, the whole still in under 1,000 characters for Figma's image prompt field; or full, every clause spelled out for surfaces without a cap.",
    ],
    "Composition and framing": [
      "Every scene is written as a FRAME, not a scene list: the camera position first, then what fills which part of the frame, where the phone sits and how small (the board holds it around a fifth of the frame width), and which edge cuts the person (above the chin, at the brow, at the hips, at the knee).",
      "The curious angle is the mood: the board's frames are POV down the body, over the shoulder, from below, straight down, chest-height torso, low beside. A snapshot's eye-level three-quarter is the one position never used.",
      "People counts are stated out loud by the People dial (exactly two, a second hand pointing) because neither vendor documents hand-count control and stating it is the only lever.",
    ],
    "Why the light varies and still reads as one system": [
      "The system half is fixed in every prompt: soft, one key, large source, lifted shadows, no hard edge, violet in the cool half, film grade. The scene half is one clause naming the source. So a bedroom lit by a phone face and a metro lit by ceiling panels share contrast, shadow quality and colour logic and differ only in where the light comes from, which is exactly how one photographer shooting one campaign across seven locations would work.",
      "The violet is stated positively as the cool half of a warm-cool split, never as an absence and never as a hard tint.",
    ],
    "Keeping a set consistent": [
      "For the first still of a scene, attach the moodboard frame closest to it in moodboard mode. For the rest of the set, anchor to the best output so the grade and softness lock while the scene changes.",
      "Change one dial at a time. Re-anchor to the same still rather than chaining outputs, because chained edits are documented to accumulate drift.",
      "Every prompt is a fresh chat for the Figma agent (Agam, 2026-09-04). Nothing carries over between generations: no memory of the last prompt, the last image or the last correction. So every block restates the whole system in full, every reference image is re-attached in the same chat as its block, and a fix is a changed token in a re-pasted block, never an instruction to adjust the last result.",
      "If a still still reads AI, ablate one lever rather than adding adjectives; the levers are named in the finish clause and each was sourced.",
    ],
    Sources: [
      "2026-09-07, five scenes added from the case's own user research (Claude/Case Studies/2026-06-29_scheduled-delivery-user-research.md; the quotes on the scene chips are verbatim: Parv on back-to-back meetings, Devanshu on peak hours and traffic, Anjali on gifting, and the deck's three \"When I'm heading to sleep\", \"When I haven't reached home yet\", \"When the store's down and it's back in fifteen minutes\"), plus a family lunch with the kids' hands at the table at Agam's ask. Peak hour is a travel scene and takes the journey's jam clause and light.",
      "2026-09-04 (later), the Time of day layer: research/schedule-images-light.md, the sun overhead after 8 a.m. with the ground bouncing it back (Chandran, Das), golden hour of about thirty minutes at these latitudes, monsoon overcast at 6500 K with no shadows (Kumar), blue hour against the first lamps.",
      "2026-09-04 (later), the Journey dial: the case's three personas from the Scheduled Delivery PRD (src/prd/scheduledPrdData.js, personaMatrix: the commuter, the coverage-edge regular, the weekly-shop planner) and the commute methods and home types from research/schedule-images-material-culture.md (the local, the metro's pink seats, the black-and-yellow auto, the cab's yellow plate, the Activa, the red city bus; mosaic, red-oxide and PG rooms).",
      "2026-09-04 (later), the recognisability rule: Agam's Airbnb framework as written in the Away icon system (image/icons.data.js, The global rule and Composition), itself built after the Airbnb service-icon set; internal source, not a research dossier.",
      "2026-09-04 (later), the phone dial and the density rule, from research/schedule-images-phone-and-density.md: no vendor documents phones or screens; the screen-replacement compositor's dark plate (Roslund, Fstoppers); named-slab mockup practice on Nano Banana and GPT Image 2; OpenAI's object-interaction and gaze idiom; a Google specialist's Delta E test of text hex codes against swatches; the vendors' one-subject-one-action-one-place structures and iterate-rather-than-overload; POV and overhead failure evidence from a sibling video medium, marked inference.",
      "2026-09-04, the Indian colour documentary look and the scene rewrite, from four dossiers in research/: schedule-images-colour-photography.md (Raghubir Singh's colour that puts foreground and background on one plane, colour rhymes, one accent in a muted field, and the cliches named by Gauri Gill, Vasantha Yogananthan, Shriya Zamindar, Deepti Dadlani and Bharat Sikka), schedule-images-light.md (Anil Mehta's two tube lights and a bulb, Ravi K. Chandran's day-interior and single-tube rules, Michal Sobocinski's rule of lighting only from the sources in frame, the tube's green cast, sodium replaced by white LED across Indian cities by 2025), schedule-images-material-culture.md (mosaic floors with brass strips, distemper, the steel almirah, MS grills, the purple-and-white local, the kirana shutter, the printed paper delivery bag), and schedule-images-emotion-and-levers.md (Barthes' punctum and blind field, Berger's tethered gesture, Hido's lit window, Leiter and Eggleston's single accent; OpenAI's grounded register and Google's mood slot; film-stock names and Kelvin values absent from every vendor page, so kept out).",
      "The Objects assortment and the five extra scenes (tiffin, post-workout, festival prep, rainy window, balcony chai) were added the same day at Agam's ask for a diverse scheduled-delivery assortment; the object cues follow the campaign group's shape-only rule.",
      "Derived 2026-08-16 from a six-frame phone-in-hand moodboard supplied by Agam (fintech and streaming campaign stills), read for what recurs: no face carrying the frame, hands and clothes as the person, small phone in a coloured case, everyday clutter, soft muted film grade, unusual camera positions.",
      "Light system: research/zepto-campaign.md, Lifestyle scenarios (practicals and motivated light from cinematography guides, D65 displays against tungsten as the warm-cool split, inverse-square falloff, blue hour, the moving-vehicle shutter rule, north-window and side-window food setups) and research/composition.md (a hard shadow comes from a small far source, so softness is written as source size).",
      "Realism: research/zepto-campaign.md, Realism (the Northwestern/MIT taxonomy of generated-image tells, Poynter's hands and backgrounds, OpenAI's gpt-image-2 guidance on candid, real texture, 35mm film and grain, Google's texture slot). No vendor documents hand-count control; hand counts are stated in the prompt.",
      "Reference handling: research/models.md rules 4, 5 and 20 (name every reference's role, restate invariants, re-anchor rather than chain). The lesson that a real photo attached pulls GPT Image toward photorealism came from the 3D faces group, where it was the problem.",
      "Colour values are stand-ins sampled from this portfolio's own Zepto tokens (#7C3AED, #2A1430, #F4F1FA) pending real brand values; they live in one place, zeptoCampaignViews.js COLORWAYS, shared with the campaign tiles.",
    ],
  },
];
